In [1]:
#Import modules:
import pandas as pd
import numpy as np
import scipy as sp
import sklearn

In [2]:
#import data and merge the macro onto the train and test
trainsm_df = pd.read_csv("train_small.csv", parse_dates=['timestamp'])
testsm_df = pd.read_csv("test_small.csv", parse_dates=['timestamp'])
macrosm_df = pd.read_csv("macro_small.csv", parse_dates=['timestamp'])
trainsm_df = pd.merge(trainsm_df, macrosm_df, how='left', on='timestamp')
testsm_df = pd.merge(testsm_df, macrosm_df, how='left', on='timestamp')
print(trainsm_df.shape, testsm_df.shape)

((30471, 132), (7662, 131))

In [3]:
#attach the okrug region
okurg_df = pd.read_csv("okurg.csv")
trainsm_df = pd.merge(trainsm_df, okurg_df, how='left', on='sub_area')
testsm_df = pd.merge(testsm_df, okurg_df, how='left', on='sub_area')

In [4]:
#import chase data
chase_imputed = pd.read_csv("chase_imputed.csv")

In [5]:
chase_imputed.describe()

                 id       full_sq      kitch_sq         floor     max_floor
count  30167.000000  30167.000000  30167.000000  30167.000000  30167.000000
mean   15283.201313     53.860510      9.932460      7.429807     13.245305
std     8790.881707     21.265281      5.974744      5.316918      5.878875
min        1.000000     10.000000      1.481618      1.000000      1.000000
25%     7690.500000     38.000000      6.000000      3.000000      9.000000
50%    15307.000000     49.000000      8.846154      6.000000     14.000000
75%    22889.500000     63.000000     11.470588     11.000000     17.000000
max    30473.000000    407.000000    209.000000     44.000000     57.000000

In [8]:
trainsm_merge = trainsm_df.drop(["full_sq", "kitch_sq", "floor", "max_floor"], axis=1)

In [9]:
train_chase = pd.merge(chase_imputed, trainsm_merge, how='left', on='id')

In [10]:
train_chase.describe()

,id,full_sq,kitch_sq,floor,max_floor,life_sq,material,build_year,num_room,state,...,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly
count,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000,23814.000000,20785.000000,1.676500e+04,20785.000000,16804.000000,...,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000,30167.000000
mean,15283.201313,53.860510,9.932460,7.429807,13.245305,33.872680,1.824970,3.077479e+03,1.910994,2.109795,...,12.532911,163.372203,9.665275,9.272730,12.618051,4.333829,9.965869,71.518245,0.291293,16.967677
std,8790.881707,21.265281,5.974744,5.316918,5.878875,18.719011,1.479219,1.548521e+05,0.851665,0.879127,...,0.654309,20.477353,4.574828,2.476184,4.327460,2.658921,4.439165,12.136821,0.149831,5.014408
min,1.000000,10.000000,1.481618,1.000000,1.000000,0.000000,1.000000,0.000000e+00,0.000000,1.000000,...,11.400000,100.080000,3.808905,5.080692,9.982029,0.767611,4.262096,67.400112,0.220400,10.567959
25%,7690.500000,38.000000,6.000000,3.000000,9.000000,20.000000,1.000000,1.967000e+03,1.000000,1.000000,...,12.220000,149.100000,3.808905,6.802652,9.982029,1.769683,4.262096,67.400112,0.220400,10.567959
50%,15307.000000,49.000000,8.846154,6.000000,14.000000,30.000000,1.000000,1.979000e+03,2.000000,2.000000,...,12.300000,160.690000,8.009779,10.395346,10.704748,6.599686,8.039559,68.573449,0.248999,16.823747
75%,22889.500000,63.000000,11.470588,11.000000,17.000000,43.000000,2.000000,2.005000e+03,2.000000,3.000000,...,12.620000,174.220000,14.488195,10.395346,14.312976,6.599686,14.648207,71.295861,0.257487,20.825967
max,30473.000000,407.000000,209.000000,44.000000,57.000000,407.000000,6.000000,2.005201e+07,19.000000,33.000000,...,14.710000,212.870000,14.488195,14.482090,24.372704,7.036363,14.648207,146.135335,0.717897,27.602766

In [11]:
missing = train_chase.isnull().sum()
print(missing.to_string())
print len(train_chase)

id                                                0
full_sq                                           0
kitch_sq                                          0
floor                                             0
max_floor                                         0
timestamp                                         0
life_sq                                        6353
material                                       9382
build_year                                    13402
num_room                                       9382
state                                         13363
product_type                                      0
sub_area                                          0
area_m                                            0
raion_popul                                       0
green_zone_part                                   0
indust_part                                       0
children_preschool                                0
preschool_quota                                6566
preschool_education_centers_raion                 0
children_school                                   0
school_quota                                   6563
school_education_centers_raion                    0
school_education_centers_top_20_raion             0
hospital_beds_raion                           14264
healthcare_centers_raion                          0
university_top_20_raion                           0
sport_objects_raion                               0
additional_education_raion                        0
shopping_centers_raion                            0
office_raion                                      0
full_all                                          0
male_f                                            0
female_f                                          0
young_all                                         0
work_all                                          0
work_male                                         0
work_female                                       0
ekder_all                                         0
raion_build_count_with_material_info           4920
build_count_block                              4920
build_count_wood                               4920
build_count_frame                              4920
build_count_brick                              4920
build_count_monolith                           4920
build_count_panel                              4920
build_count_foam                               4920
build_count_slag                               4920
build_count_mix                                4920
raion_build_count_with_builddate_info          4920
build_count_before_1920                        4920
build_count_1921-1945                          4920
build_count_1946-1970                          4920
build_count_1971-1995                          4920
build_count_after_1995                         4920
metro_min_avto                                    0
metro_km_avto                                     0
metro_min_walk                                   25
metro_km_walk                                    25
kindergarten_km                                   0
school_km                                         0
park_km                                           0
green_zone_km                                     0
industrial_km                                     0
water_treatment_km                                0
cemetery_km                                       0
incineration_km                                   0
railroad_station_walk_km                         25
railroad_station_walk_min                        25
railroad_station_avto_km                          0
railroad_station_avto_min                         0
public_transport_station_km                       0
public_transport_station_min_walk                 0
water_km                                          0
mkad_km                                           0
ttk_km                                            0
sadovoe_km                                        0
bulvar_ring_km                                    0
kremlin_km                                        0
big_road1_km                                      0
big_road2_km                                      0
railroad_km                                       0
zd_vokzaly_avto_km                                0
bus_terminal_avto_km                              0
oil_chemistry_km                                  0
nuclear_reactor_km                                0
radiation_km                                      0
power_transmission_line_km                        0
thermal_power_plant_km                            0
ts_km                                             0
big_market_km                                     0
market_shop_km                                    0
fitness_km                                        0
swim_pool_km                                      0
ice_rink_km                                       0
stadium_km                                        0
basketball_km                                     0
hospice_morgue_km                                 0
detention_facility_km                             0
public_healthcare_km                              0
university_km                                     0
workplaces_km                                     0
shopping_centers_km                               0
office_km                                         0
additional_education_km                           0
preschool_km                                      0
big_church_km                                     0
church_synagogue_km                               0
mosque_km                                         0
theater_km                                        0
museum_km                                         0
exhibition_km                                     0
catering_km                                       0
ecology                                        7532
price_doc                                         0
oil_urals                                         0
cpi                                               0
ppi                                               0
eurrub                                            0
brent                                             0
average_provision_of_build_contract_moscow        0
micex                                             0
mortgage_rate                                     0
rent_price_4+room_bus                             0
sd_oil_yearly                                     0
sd_cpi_yearly                                     0
sd_ppi_yearly                                     0
sd_eurrub_yearly                                  0
sd_brent_yearly                                   0
sd_micex_yearly                                   0
sd_mortgage_yearly                                0
sd_rent_yearly                                    0
okurg_district                                    0
30167

In [12]:
train_clean = train_chase.dropna(subset = ['metro_min_walk'])

In [30]:
missing = testsm_df.isnull().sum()
print(missing.to_string())

id                                               0
timestamp                                        0
full_sq                                          0
life_sq                                       1176
floor                                            0
max_floor                                        0
material                                         0
build_year                                    1049
num_room                                         0
kitch_sq                                         0
state                                          694
product_type                                    33
sub_area                                         0
area_m                                           0
raion_popul                                      0
green_zone_part                                  0
indust_part                                      0
children_preschool                               0
preschool_quota                               1596
preschool_education_centers_raion                0
children_school                                  0
school_quota                                  1595
school_education_centers_raion                   0
school_education_centers_top_20_raion            0
hospital_beds_raion                           3418
healthcare_centers_raion                         0
university_top_20_raion                          0
sport_objects_raion                              0
additional_education_raion                       0
shopping_centers_raion                           0
office_raion                                     0
full_all                                         0
male_f                                           0
female_f                                         0
young_all                                        0
work_all                                         0
work_male                                        0
work_female                                      0
ekder_all                                        0
raion_build_count_with_material_info          1218
build_count_block                             1218
build_count_wood                              1218
build_count_frame                             1218
build_count_brick                             1218
build_count_monolith                          1218
build_count_panel                             1218
build_count_foam                              1218
build_count_slag                              1218
build_count_mix                               1218
raion_build_count_with_builddate_info         1218
build_count_before_1920                       1218
build_count_1921-1945                         1218
build_count_1946-1970                         1218
build_count_1971-1995                         1218
build_count_after_1995                        1218
metro_min_avto                                   0
metro_km_avto                                    0
metro_min_walk                                  34
metro_km_walk                                   34
kindergarten_km                                  0
school_km                                        0
park_km                                          0
green_zone_km                                    0
industrial_km                                    0
water_treatment_km                               0
cemetery_km                                      0
incineration_km                                  0
railroad_station_walk_km                        34
railroad_station_walk_min                       34
railroad_station_avto_km                         0
railroad_station_avto_min                        0
public_transport_station_km                      0
public_transport_station_min_walk                0
water_km                                         0
mkad_km                                          0
ttk_km                                           0
sadovoe_km                                       0
bulvar_ring_km                                   0
kremlin_km                                       0
big_road1_km                                     0
big_road2_km                                     0
railroad_km                                      0
zd_vokzaly_avto_km                               0
bus_terminal_avto_km                             0
oil_chemistry_km                                 0
nuclear_reactor_km                               0
radiation_km                                     0
power_transmission_line_km                       0
thermal_power_plant_km                           0
ts_km                                            0
big_market_km                                    0
market_shop_km                                   0
fitness_km                                       0
swim_pool_km                                     0
ice_rink_km                                      0
stadium_km                                       0
basketball_km                                    0
hospice_morgue_km                                0
detention_facility_km                            0
public_healthcare_km                             0
university_km                                    0
workplaces_km                                    0
shopping_centers_km                              0
office_km                                        0
additional_education_km                          0
preschool_km                                     0
big_church_km                                    0
church_synagogue_km                              0
mosque_km                                        0
theater_km                                       0
museum_km                                        0
exhibition_km                                    0
catering_km                                      0
ecology                                       1765
oil_urals                                        0
cpi                                              0
ppi                                              0
eurrub                                           0
brent                                            0
average_provision_of_build_contract_moscow       0
micex                                            0
mortgage_rate                                    0
rent_price_4+room_bus                            0
sd_oil_yearly                                    0
sd_cpi_yearly                                    0
sd_ppi_yearly                                    0
sd_eurrub_yearly                                 0
sd_brent_yearly                                  0
sd_micex_yearly                                  0
sd_mortgage_yearly                               0
sd_rent_yearly                                   0
okurg_district                                   0

In [31]:
testsm_df.describe() #need to fix up kitch_sq, full_sq, max_floor

,id,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,state,...,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly
count,7662.000000,7662.000000,6486.000000,7662.000000,7662.000000,7662.000000,6613.000000,7662.000000,7662.000000,6968.000000,...,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000
mean,34304.500000,53.701164,32.660037,7.652571,12.591099,1.854216,1820.888099,1.876403,6.938662,1.985792,...,12.726691,181.616325,6.960293,10.357489,21.469072,6.039786,7.231745,81.374219,0.484803,29.842628
std,2211.973214,20.104320,22.737855,5.099418,6.659291,1.517171,552.993964,0.835665,25.579688,0.820086,...,0.394161,28.196758,1.008706,3.964332,2.790806,0.957853,0.776425,9.686745,0.224037,2.152828
min,30474.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,...,12.100000,142.850000,5.990909,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766
25%,32389.250000,39.200000,19.900000,4.000000,9.000000,1.000000,1966.000000,1.000000,1.000000,1.000000,...,12.290000,164.260000,5.990909,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766
50%,34304.500000,50.410000,30.400000,7.000000,14.000000,1.000000,1982.000000,2.000000,7.000000,2.000000,...,12.860000,174.650000,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534
75%,36219.750000,63.300000,41.800000,11.000000,17.000000,2.000000,2011.000000,2.000000,9.500000,3.000000,...,12.920000,205.640000,8.009779,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534
max,38135.000000,403.000000,869.000000,41.000000,48.000000,6.000000,2019.000000,19.000000,1968.000000,4.000000,...,13.440000,242.230000,8.009779,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534

In [32]:
testsm_df.loc[testsm_df['max_floor'] < testsm_df['floor']] #need to fix 643 out of 7662
#notice that the kitchen square is the same as the max floor for these

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,okurg_district
5,30479,2015-07-01,48.43,NaN,21,1,1,2015.0,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Western
7,30481,2015-07-01,43.10,NaN,5,0,1,NaN,1,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
14,30488,2015-07-01,69.30,NaN,7,1,1,NaN,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
15,30489,2015-07-02,69.30,NaN,10,0,1,NaN,2,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
16,30490,2015-07-02,117.40,NaN,10,0,1,NaN,3,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Eastern
32,30506,2015-07-02,53.82,NaN,3,1,1,NaN,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Troitsky
44,30518,2015-07-03,35.82,1.00,14,1,1,2015.0,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Western
68,30542,2015-07-06,34.80,NaN,3,0,1,NaN,1,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Troitsky
72,30546,2015-07-06,41.90,41.90,9,0,1,0.0,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
73,30547,2015-07-06,61.70,NaN,7,1,1,2015.0,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,North Eastern
88,30562,2015-07-07,62.40,NaN,23,0,1,NaN,2,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Southern
89,30563,2015-07-07,40.00,1.00,9,1,1,NaN,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Central
135,30609,2015-07-10,69.30,NaN,8,0,1,NaN,2,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
151,30625,2015-07-13,68.47,NaN,7,1,1,NaN,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
156,30630,2015-07-13,41.90,NaN,15,1,1,NaN,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Central
166,30640,2015-07-14,49.40,NaN,9,0,1,NaN,1,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
177,30651,2015-07-14,54.66,NaN,3,1,1,0.0,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Troitsky
179,30653,2015-07-14,49.85,NaN,14,1,1,NaN,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Western
184,30658,2015-07-14,64.90,NaN,11,1,1,NaN,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,South Western
193,30667,2015-07-15,42.99,NaN,8,1,1,NaN,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
194,30668,2015-07-15,61.70,1.00,6,1,1,2017.0,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,North Eastern
201,30675,2015-07-15,34.80,NaN,3,1,1,NaN,1,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Troitsky
207,30681,2015-07-16,27.79,NaN,11,0,1,NaN,1,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
212,30686,2015-07-16,54.80,NaN,15,1,1,NaN,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Southern
241,30715,2015-07-17,52.21,NaN,11,0,1,NaN,2,0.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
254,30728,2015-07-20,74.61,1.00,3,1,1,2015.0,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,North Eastern
267,30741,2015-07-21,76.65,NaN,3,1,1,2015.0,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Western
274,30748,2015-07-21,109.10,66.40,6,1,1,2015.0,3,15.90,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Northern
288,30762,2015-07-22,73.60,NaN,10,1,1,NaN,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
303,30777,2015-07-24,69.30,1.00,12,1,1,2015.0,2,1.00,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7501,37975,2016-05-06,44.73,NaN,7,1,1,NaN,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,North Eastern
7502,37976,2016-05-06,39.72,1.00,5,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Zelenograd
7513,37987,2016-05-06,77.51,1.00,9,1,1,1.0,3,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Zelenograd
7519,37993,2016-05-07,47.50,NaN,16,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7521,37995,2016-05-07,58.30,NaN,2,0,1,NaN,2,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Novomoskovsky
7525,37999,2016-05-07,77.51,77.51,3,0,1,0.0,3,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Zelenograd
7543,38017,2016-05-10,39.70,NaN,8,1,1,2016.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,North Western
7546,38020,2016-05-10,47.83,1.00,15,1,1,1.0,2,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7548,38022,2016-05-11,62.30,1.00,14,1,1,1.0,2,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7556,38030,2016-05-11,39.20,15.30,18,1,1,2017.0,1,12.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7566,38040,2016-05-12,60.58,NaN,2,0,1,NaN,3,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Novomoskovsky
7569,38043,2016-05-12,77.51,1.00,3,1,1,1.0,3,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7583,38057,2016-05-14,38.77,1.00,7,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7586,38060,2016-05-14,43.71,1.00,8,1,1,2016.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,North Eastern
7588,38062,2016-05-16,54.05,NaN,16,0,1,NaN,2,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Novomoskovsky
7590,38064,2016-05-16,66.37,NaN,13,0,1,NaN,2,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,South Eastern
7596,38070,2016-05-17,77.25,1.00,9,1,1,1.0,3,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7610,38084,2016-05-18,38.30,NaN,4,0,1,NaN,2,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Novomoskovsky
7612,38086,2016-05-18,49.87,18.66,14,1,1,2016.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7614,38088,2016-05-18,38.30,NaN,2,0,1,NaN,1,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Southern
7616,38090,2016-05-18,46.40,1.00,4,1,1,1.0,2,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7622,38096,2016-05-18,39.90,NaN,8,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Novomoskovsky
7630,38104,2016-05-20,50.80,17.81,3,1,2,2017.0,1,14.89,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7640,38114,2016-05-23,77.51,1.00,4,1,1,1.0,3,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7646,38120,2016-05-23,69.70,1.00,8,1,4,2016.0,2,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,North Eastern
7648,38122,2016-05-23,33.89,1.00,3,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7649,38123,2016-05-24,27.27,NaN,14,1,1,NaN,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,South Eastern
7653,38127,2016-05-25,19.91,1.00,8,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central
7658,38132,2016-05-28,54.09,NaN,14,0,1,NaN,2,0.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Novomoskovsky
7659,38133,2016-05-30,41.08,1.00,12,1,1,1.0,1,1.00,...,205.89,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Central

In [34]:
643.0/7662.0 #8% of the test data has messed up kitchen, max floor

0.0839206473505612

In [35]:
testsm_df.loc[testsm_df['floor'] < 1] #floor doesn't seem to be messed up...

Empty DataFrame
Columns: [id, timestamp, full_sq, life_sq, floor, max_floor, material, build_year, num_room, kitch_sq, state, product_type, sub_area, area_m, raion_popul, green_zone_part, indust_part, children_preschool, preschool_quota, preschool_education_centers_raion, children_school, school_quota, school_education_centers_raion, school_education_centers_top_20_raion, hospital_beds_raion, healthcare_centers_raion, university_top_20_raion, sport_objects_raion, additional_education_raion, shopping_centers_raion, office_raion, full_all, male_f, female_f, young_all, work_all, work_male, work_female, ekder_all, raion_build_count_with_material_info, build_count_block, build_count_wood, build_count_frame, build_count_brick, build_count_monolith, build_count_panel, build_count_foam, build_count_slag, build_count_mix, raion_build_count_with_builddate_info, build_count_before_1920, build_count_1921-1945, build_count_1946-1970, build_count_1971-1995, build_count_after_1995, metro_min_avto, metro_km_avto, metro_min_walk, metro_km_walk, kindergarten_km, school_km, park_km, green_zone_km, industrial_km, water_treatment_km, cemetery_km, incineration_km, railroad_station_walk_km, railroad_station_walk_min, railroad_station_avto_km, railroad_station_avto_min, public_transport_station_km, public_transport_station_min_walk, water_km, mkad_km, ttk_km, sadovoe_km, bulvar_ring_km, kremlin_km, big_road1_km, big_road2_km, railroad_km, zd_vokzaly_avto_km, bus_terminal_avto_km, oil_chemistry_km, nuclear_reactor_km, radiation_km, power_transmission_line_km, thermal_power_plant_km, ts_km, big_market_km, market_shop_km, fitness_km, swim_pool_km, ice_rink_km, stadium_km, basketball_km, hospice_morgue_km, detention_facility_km, public_healthcare_km, ...]
Index: []

[0 rows x 132 columns]

In [36]:
testsm_df.loc[testsm_df['full_sq'] < testsm_df['life_sq']] #fix full square, get rid of life square

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,okurg_district
64,30538,2015-07-06,29.80,30.60,3,5,2,1960.0,1,5.3,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,North Western
119,30593,2015-07-09,100.04,104.28,2,2,2,0.0,3,1.0,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Northern
171,30645,2015-07-14,57.80,60.00,3,12,1,2000.0,2,1.0,...,211.83,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,South Western
464,30938,2015-08-05,0.00,37.80,7,19,1,0.0,1,0.0,...,205.64,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
601,31075,2015-08-17,74.20,742.00,2,17,1,NaN,2,1.0,...,205.64,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
1896,32370,2015-10-23,36.10,361.00,14,14,4,0.0,1,0.0,...,242.23,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky
2027,32501,2015-10-30,51.90,93.20,12,20,1,2015.0,3,1.0,...,242.23,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,North Western
2031,32505,2015-10-30,40.20,237.00,11,11,1,2016.0,2,67.0,...,242.23,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,North Western
2791,33265,2015-12-01,86.90,869.00,3,20,4,0.0,3,0.0,...,172.89,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Southern
2804,33278,2015-12-01,14.80,33.80,11,15,1,2015.0,1,8.0,...,172.89,8.009779,14.482090,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Southern
5187,35661,2016-02-15,56.30,283.00,7,17,1,2014.0,2,8.3,...,149.88,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Eastern
5383,35857,2016-02-18,1.00,42.07,18,18,1,NaN,3,1.0,...,149.88,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,Western

In [37]:
testsm_df.loc[testsm_df['full_sq'] < 1] #fix full square, get rid of life square

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,okurg_district
464,30938,2015-08-05,0.0,37.8,7,19,1,0.0,1,0.0,...,205.64,8.009779,14.48209,24.372704,7.036363,8.039559,71.295861,0.717897,27.602766,Novomoskovsky

In [38]:
testsm_df.loc[testsm_df['full_sq'] > 300] #fix full square, get rid of life square

,id,timestamp,full_sq,life_sq,floor,max_floor,material,build_year,num_room,kitch_sq,...,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,okurg_district
4196,34670,2016-01-25,314.5,122.6,3,3,2,2010.0,5,34.8,...,164.26,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.2695,31.911534,Troitsky
4634,35108,2016-02-02,403.0,1.0,7,1,1,1.0,2,1.0,...,149.88,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.2695,31.911534,Central

In [15]:
test_clean = testsm_df.dropna(subset = ['metro_min_walk'])

In [13]:
train_clean = train_clean.dropna(axis=1, how='any')

In [16]:
test_clean = test_clean.dropna(axis=1, how='any')
test_clean = test_clean.drop(["material", "num_room"], axis=1)

In [14]:
train_clean.describe()

,id,full_sq,kitch_sq,floor,max_floor,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly
count,30142.00000,30142.000000,30142.000000,30142.000000,30142.000000,3.014200e+04,30142.000000,30142.000000,30142.000000,30142.000000,...,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000
mean,15276.83737,53.852465,9.927737,7.429865,13.245442,1.761762e+07,84236.673114,0.218597,0.119145,5150.860660,...,12.532483,163.360429,9.663918,9.270817,12.615605,4.332140,9.964648,71.519952,0.291200,16.964993
std,8789.95339,21.242620,5.960647,5.316839,5.878794,2.056637e+07,57882.834891,0.175095,0.118793,3818.881213,...,0.653758,20.469919,4.575206,2.475374,4.324236,2.659083,4.439491,12.141640,0.149703,5.012847
min,1.00000,10.000000,1.481618,1.000000,1.000000,2.081628e+06,2546.000000,0.001879,0.000000,175.000000,...,11.400000,100.080000,3.808905,5.080692,9.982029,0.767611,4.262096,67.400112,0.220400,10.567959
25%,7683.25000,38.000000,6.000000,3.000000,9.000000,7.307411e+06,21819.000000,0.063755,0.019509,1706.000000,...,12.220000,149.100000,3.808905,6.802652,9.982029,1.769683,4.262096,67.400112,0.220400,10.567959
50%,15298.50000,49.000000,8.847859,6.000000,14.000000,1.041657e+07,83502.000000,0.167526,0.072158,4926.000000,...,12.300000,160.690000,8.009779,10.395346,10.704748,6.599686,8.039559,68.573449,0.248999,16.823747
75%,22882.75000,63.000000,11.470588,11.000000,17.000000,1.803644e+07,122862.000000,0.336177,0.195781,7103.000000,...,12.620000,174.220000,14.488195,10.395346,14.312976,6.599686,14.648207,71.295861,0.257487,20.825967
max,30473.00000,407.000000,209.000000,44.000000,57.000000,2.060718e+08,247469.000000,0.852923,0.521867,19223.000000,...,14.710000,212.870000,14.488195,14.482090,24.372704,7.036363,14.648207,146.135335,0.717897,27.602766

In [17]:
test_clean.describe()

,id,full_sq,floor,max_floor,kitch_sq,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly
count,7628.000000,7628.00000,7628.000000,7628.000000,7628.000000,7.628000e+03,7628.000000,7628.000000,7628.000000,7628.000000,...,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000
mean,34302.871919,53.65292,7.627819,12.557289,6.928150,1.771468e+07,87567.132407,0.224865,0.122595,5358.472208,...,12.726492,181.635069,6.961703,10.363029,21.472972,6.041124,7.232830,81.360684,0.485116,29.839620
std,2211.414306,20.08461,5.072910,6.634237,25.633762,2.215143e+07,56419.270784,0.177155,0.126425,3776.316459,...,0.394251,28.209808,1.008761,3.964550,2.790959,0.957906,0.776467,9.687276,0.224049,2.152946
min,30474.000000,0.00000,1.000000,0.000000,0.000000,2.081628e+06,2546.000000,0.001879,0.000000,175.000000,...,12.100000,142.850000,5.990909,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766
25%,32387.750000,39.20000,3.000000,9.000000,1.000000,7.307411e+06,37502.000000,0.068202,0.012339,2448.000000,...,12.290000,164.260000,5.990909,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766
50%,34300.500000,50.30000,7.000000,14.000000,7.000000,1.004686e+07,85956.000000,0.157332,0.072158,4992.000000,...,12.860000,174.650000,5.990909,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534
75%,36220.250000,63.20000,11.000000,17.000000,9.500000,1.788191e+07,118945.000000,0.349935,0.195781,7125.000000,...,12.920000,205.640000,8.009779,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534
max,38135.000000,403.00000,41.000000,48.000000,1968.000000,2.060718e+08,247469.000000,0.852923,0.521867,19223.000000,...,13.440000,242.230000,8.009779,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534

In [18]:
#Population Density (will be the same throughout each SubArea)
train_clean["pop_density"] = train_clean["raion_popul"] / train_clean["area_m"].astype("float")
test_clean["pop_density"] = test_clean["raion_popul"] / test_clean["area_m"].astype("float")

In [19]:
#Ratio of elder population (will be the same throughout each SubArea)
train_clean["elder_ratio"] = train_clean["ekder_all"] / (train_clean["young_all"] + train_clean["work_all"] + train_clean["ekder_all"]).astype("float")
test_clean["elder_ratio"] = test_clean["ekder_all"] / (test_clean["young_all"] + test_clean["work_all"] + test_clean["ekder_all"]).astype("float")

In [20]:
#Ratio of under 18 population (will be the same throughout each SubArea)
train_clean["youth_ratio"] = train_clean["young_all"] / (train_clean["young_all"] + train_clean["work_all"] + train_clean["ekder_all"]).astype("float")
test_clean["youth_ratio"] = test_clean["young_all"] / (test_clean["young_all"] + test_clean["work_all"] + test_clean["ekder_all"]).astype("float")

In [21]:
test_clean.describe()

,id,full_sq,floor,max_floor,kitch_sq,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,pop_density,elder_ratio,youth_ratio
count,7628.000000,7628.00000,7628.000000,7628.000000,7628.000000,7.628000e+03,7628.000000,7628.000000,7628.000000,7628.000000,...,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000,7628.000000
mean,34302.871919,53.65292,7.627819,12.557289,6.928150,1.771468e+07,87567.132407,0.224865,0.122595,5358.472208,...,10.363029,21.472972,6.041124,7.232830,81.360684,0.485116,29.839620,0.009965,0.227630,0.134638
std,2211.414306,20.08461,5.072910,6.634237,25.633762,2.215143e+07,56419.270784,0.177155,0.126425,3776.316459,...,3.964550,2.790959,0.957906,0.776467,9.687276,0.224049,2.152946,0.006828,0.035683,0.020160
min,30474.000000,0.00000,1.000000,0.000000,0.000000,2.081628e+06,2546.000000,0.001879,0.000000,175.000000,...,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766,0.000015,0.114854,0.078007
25%,32387.750000,39.20000,3.000000,9.000000,1.000000,7.307411e+06,37502.000000,0.068202,0.012339,2448.000000,...,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766,0.004109,0.215179,0.123241
50%,34300.500000,50.30000,7.000000,14.000000,7.000000,1.004686e+07,85956.000000,0.157332,0.072158,4992.000000,...,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,0.010315,0.226332,0.136339
75%,36220.250000,63.20000,11.000000,17.000000,9.500000,1.788191e+07,118945.000000,0.349935,0.195781,7125.000000,...,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534,0.014549,0.255141,0.143464
max,38135.000000,403.00000,41.000000,48.000000,1968.000000,2.060718e+08,247469.000000,0.852923,0.521867,19223.000000,...,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534,0.028298,0.320316,0.260695

In [22]:
train_clean.describe()

,id,full_sq,kitch_sq,floor,max_floor,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,pop_density,elder_ratio,youth_ratio
count,30142.00000,30142.000000,30142.000000,30142.000000,30142.000000,3.014200e+04,30142.000000,30142.000000,30142.000000,30142.000000,...,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000
mean,15276.83737,53.852465,9.927737,7.429865,13.245442,1.761762e+07,84236.673114,0.218597,0.119145,5150.860660,...,9.270817,12.615605,4.332140,9.964648,71.519952,0.291200,16.964993,0.009732,0.225962,0.135966
std,8789.95339,21.242620,5.960647,5.316839,5.878794,2.056637e+07,57882.834891,0.175095,0.118793,3818.881213,...,2.475374,4.324236,2.659083,4.439491,12.141640,0.149703,5.012847,0.007173,0.036994,0.021070
min,1.00000,10.000000,1.481618,1.000000,1.000000,2.081628e+06,2546.000000,0.001879,0.000000,175.000000,...,5.080692,9.982029,0.767611,4.262096,67.400112,0.220400,10.567959,0.000015,0.114854,0.078007
25%,7683.25000,38.000000,6.000000,3.000000,9.000000,7.307411e+06,21819.000000,0.063755,0.019509,1706.000000,...,6.802652,9.982029,1.769683,4.262096,67.400112,0.220400,10.567959,0.001750,0.215179,0.123241
50%,15298.50000,49.000000,8.847859,6.000000,14.000000,1.041657e+07,83502.000000,0.167526,0.072158,4926.000000,...,10.395346,10.704748,6.599686,8.039559,68.573449,0.248999,16.823747,0.010058,0.225870,0.138872
75%,22882.75000,63.000000,11.470588,11.000000,17.000000,1.803644e+07,122862.000000,0.336177,0.195781,7103.000000,...,10.395346,14.312976,6.599686,14.648207,71.295861,0.257487,20.825967,0.014948,0.255141,0.143464
max,30473.00000,407.000000,209.000000,44.000000,57.000000,2.060718e+08,247469.000000,0.852923,0.521867,19223.000000,...,14.482090,24.372704,7.036363,14.648207,146.135335,0.717897,27.602766,0.028298,0.320316,0.260695

In [ ]:
#do a percent of floor value for train, and need to FIX TEST--how?

In [23]:
#Ratio of floor (unique to each unit)
train_clean["floor_ratio"] = train_clean["floor"] / train_clean["max_floor"].astype("float")

#Need to fix test
#test_clean["floor_ratio"] = test_clean["floor"] / test_clean["max_floor"].astype("float")

In [29]:
test_clean.loc[test_clean['max_floor'] < test_clean['floor']] #need to fix 640 out of 7628

,id,timestamp,full_sq,floor,max_floor,kitch_sq,sub_area,area_m,raion_popul,green_zone_part,...,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,okurg_district,pop_density,elder_ratio,youth_ratio,year,month
5,30479,2015-07-01,48.43,21,1,1.00,Filevskij Park,9.629358e+06,89467,0.343754,...,8.039559,71.295861,0.717897,27.602766,Western,0.009291,0.179485,0.092705,2015,7
7,30481,2015-07-01,43.10,5,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
14,30488,2015-07-01,69.30,7,1,1.00,Poselenie Filimonkovskoe,3.574795e+07,2546,0.548992,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000071,0.215240,0.143362,2015,7
15,30489,2015-07-02,69.30,10,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
16,30490,2015-07-02,117.40,10,0,0.00,Izmajlovo,1.504557e+07,102828,0.637399,...,8.039559,71.295861,0.717897,27.602766,Eastern,0.006834,0.256166,0.106858,2015,7
32,30506,2015-07-02,53.82,3,1,1.00,Poselenie Novofedorovskoe,1.487016e+08,6161,0.670840,...,8.039559,71.295861,0.717897,27.602766,Troitsky,0.000041,0.217822,0.134718,2015,7
44,30518,2015-07-03,35.82,14,1,1.00,Filevskij Park,9.629358e+06,89467,0.343754,...,8.039559,71.295861,0.717897,27.602766,Western,0.009291,0.179485,0.092705,2015,7
68,30542,2015-07-06,34.80,3,0,0.00,Poselenie Novofedorovskoe,1.487016e+08,6161,0.670840,...,8.039559,71.295861,0.717897,27.602766,Troitsky,0.000041,0.217822,0.134718,2015,7
72,30546,2015-07-06,41.90,9,0,1.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
73,30547,2015-07-06,61.70,7,1,1.00,Sviblovo,4.441296e+06,60315,0.137976,...,8.039559,71.295861,0.717897,27.602766,North Eastern,0.013580,0.204261,0.127763,2015,7
88,30562,2015-07-07,62.40,23,0,0.00,Nagornoe,5.293465e+06,77878,0.023464,...,8.039559,71.295861,0.717897,27.602766,Southern,0.014712,0.223375,0.136110,2015,7
89,30563,2015-07-07,40.00,9,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,8.039559,71.295861,0.717897,27.602766,Central,0.010315,0.267774,0.149542,2015,7
135,30609,2015-07-10,69.30,8,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
151,30625,2015-07-13,68.47,7,1,1.00,Poselenie Moskovskij,4.036700e+07,21819,0.492840,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000541,0.215179,0.143361,2015,7
156,30630,2015-07-13,41.90,15,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,8.039559,71.295861,0.717897,27.602766,Central,0.010315,0.267774,0.149542,2015,7
166,30640,2015-07-14,49.40,9,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
177,30651,2015-07-14,54.66,3,1,1.00,Poselenie Novofedorovskoe,1.487016e+08,6161,0.670840,...,8.039559,71.295861,0.717897,27.602766,Troitsky,0.000041,0.217822,0.134718,2015,7
184,30658,2015-07-14,64.90,11,1,1.00,Jasenevo,2.481385e+07,174831,0.683844,...,8.039559,71.295861,0.717897,27.602766,South Western,0.007046,0.264124,0.134318,2015,7
193,30667,2015-07-15,42.99,8,1,1.00,Poselenie Vnukovskoe,2.553630e+07,4001,0.496315,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000157,0.215196,0.143464,2015,7
194,30668,2015-07-15,61.70,6,1,1.00,Sviblovo,4.441296e+06,60315,0.137976,...,8.039559,71.295861,0.717897,27.602766,North Eastern,0.013580,0.204261,0.127763,2015,7
201,30675,2015-07-15,34.80,3,1,1.00,Poselenie Novofedorovskoe,1.487016e+08,6161,0.670840,...,8.039559,71.295861,0.717897,27.602766,Troitsky,0.000041,0.217822,0.134718,2015,7
207,30681,2015-07-16,27.79,11,0,0.00,Poselenie Filimonkovskoe,3.574795e+07,2546,0.548992,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000071,0.215240,0.143362,2015,7
212,30686,2015-07-16,54.80,15,1,1.00,Nagatinskij Zaton,9.589337e+06,115352,0.372602,...,8.039559,71.295861,0.717897,27.602766,Southern,0.012029,0.255141,0.136339,2015,7
241,30715,2015-07-17,52.21,11,0,0.00,Poselenie Filimonkovskoe,3.574795e+07,2546,0.548992,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000071,0.215240,0.143362,2015,7
254,30728,2015-07-20,74.61,3,1,1.00,Sviblovo,4.441296e+06,60315,0.137976,...,8.039559,71.295861,0.717897,27.602766,North Eastern,0.013580,0.204261,0.127763,2015,7
274,30748,2015-07-21,109.10,6,1,15.90,Levoberezhnoe,6.424174e+06,51455,0.216361,...,8.039559,71.295861,0.717897,27.602766,Northern,0.008010,0.267943,0.113419,2015,7
288,30762,2015-07-22,73.60,10,1,1.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
303,30777,2015-07-24,69.30,12,1,1.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
309,30783,2015-07-24,57.00,13,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,8.039559,71.295861,0.717897,27.602766,Novomoskovsky,0.000143,0.215220,0.143410,2015,7
319,30793,2015-07-27,67.67,21,1,1.00,Filevskij Park,9.629358e+06,89467,0.343754,...,8.039559,71.295861,0.717897,27.602766,Western,0.009291,0.179485,0.092705,2015,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7501,37975,2016-05-06,44.73,7,1,1.00,Sviblovo,4.441296e+06,60315,0.137976,...,6.485588,90.683353,0.269500,31.911534,North Eastern,0.013580,0.204261,0.127763,2016,5
7502,37976,2016-05-06,39.72,5,1,1.00,Savelki,7.759254e+06,32071,0.278315,...,6.485588,90.683353,0.269500,31.911534,Zelenograd,0.004133,0.249790,0.127841,2016,5
7513,37987,2016-05-06,77.51,9,1,1.00,Krjukovo,1.084231e+07,85219,0.062172,...,6.485588,90.683353,0.269500,31.911534,Zelenograd,0.007860,0.174973,0.143090,2016,5
7519,37993,2016-05-07,47.50,16,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7521,37995,2016-05-07,58.30,2,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,6.485588,90.683353,0.269500,31.911534,Novomoskovsky,0.000143,0.215220,0.143410,2016,5
7525,37999,2016-05-07,77.51,3,0,0.00,Krjukovo,1.084231e+07,85219,0.062172,...,6.485588,90.683353,0.269500,31.911534,Zelenograd,0.007860,0.174973,0.143090,2016,5
7543,38017,2016-05-10,39.70,8,1,1.00,Pokrovskoe Streshnevo,1.308980e+07,53786,0.183969,...,6.485588,90.683353,0.269500,31.911534,North Western,0.004109,0.254825,0.128863,2016,5
7546,38020,2016-05-10,47.83,15,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7548,38022,2016-05-11,62.30,14,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7556,38030,2016-05-11,39.20,18,1,12.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7566,38040,2016-05-12,60.58,2,0,0.00,Poselenie Vnukovskoe,2.553630e+07,4001,0.496315,...,6.485588,90.683353,0.269500,31.911534,Novomoskovsky,0.000157,0.215196,0.143464,2016,5
7569,38043,2016-05-12,77.51,3,1,1.00,Basmannoe,8.398461e+06,108171,0.015234,...,6.485588,90.683353,0.269500,31.911534,Central,0.012880,0.247386,0.123582,2016,5
7583,38057,2016-05-14,38.77,7,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7586,38060,2016-05-14,43.71,8,1,1.00,Mar'ina Roshha,4.684028e+06,65972,0.015525,...,6.485588,90.683353,0.269500,31.911534,North Eastern,0.014084,0.232674,0.108379,2016,5
7588,38062,2016-05-16,54.05,16,0,0.00,Poselenie Desjonovskoe,5.299528e+07,13890,0.349935,...,6.485588,90.683353,0.269500,31.911534,Novomoskovsky,0.000262,0.215191,0.143341,2016,5
7590,38064,2016-05-16,66.37,13,0,0.00,Lefortovo,8.993640e+06,89971,0.066941,...,6.485588,90.683353,0.269500,31.911534,South Eastern,0.010004,0.225606,0.119794,2016,5
7596,38070,2016-05-17,77.25,9,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7610,38084,2016-05-18,38.30,4,0,0.00,Poselenie Sosenskoe,6.677245e+07,9553,0.336177,...,6.485588,90.683353,0.269500,31.911534,Novomoskovsky,0.000143,0.215220,0.143410,2016,5
7612,38086,2016-05-18,49.87,14,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7614,38088,2016-05-18,38.30,2,0,0.00,Nagatinskij Zaton,9.589337e+06,115352,0.372602,...,6.485588,90.683353,0.269500,31.911534,Southern,0.012029,0.255141,0.136339,2016,5
7616,38090,2016-05-18,46.40,4,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7622,38096,2016-05-18,39.90,8,1,1.00,Poselenie Desjonovskoe,5.299528e+07,13890,0.349935,...,6.485588,90.683353,0.269500,31.911534,Novomoskovsky,0.000262,0.215191,0.143341,2016,5
7630,38104,2016-05-20,50.80,3,1,14.89,Presnenskoe,1.163805e+07,123280,0.068202,...,6.485588,90.683353,0.269500,31.911534,Central,0.010593,0.267821,0.120912,2016,5
7640,38114,2016-05-23,77.51,4,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5
7646,38120,2016-05-23,69.70,8,1,1.00,Severnoe,1.041657e+07,27992,0.146447,...,6.485588,90.683353,0.269500,31.911534,North Eastern,0.002687,0.114854,0.187125,2016,5
7648,38122,2016-05-23,33.89,3,1,1.00,Basmannoe,8.398461e+06,108171,0.015234,...,6.485588,90.683353,0.269500,31.911534,Central,0.012880,0.247386,0.123582,2016,5
7649,38123,2016-05-24,27.27,14,1,1.00,Lefortovo,8.993640e+06,89971,0.066941,...,6.485588,90.683353,0.269500,31.911534,South Eastern,0.010004,0.225606,0.119794,2016,5
7653,38127,2016-05-25,19.91,8,1,1.00,Basmannoe,8.398461e+06,108171,0.015234,...,6.485588,90.683353,0.269500,31.911534,Central,0.012880,0.247386,0.123582,2016,5
7658,38132,2016-05-28,54.09,14,0,0.00,Poselenie Desjonovskoe,5.299528e+07,13890,0.349935,...,6.485588,90.683353,0.269500,31.911534,Novomoskovsky,0.000262,0.215191,0.143341,2016,5
7659,38133,2016-05-30,41.08,12,1,1.00,Tverskoe,7.307411e+06,75377,0.065444,...,6.485588,90.683353,0.269500,31.911534,Central,0.010315,0.267774,0.149542,2016,5

In [28]:
train_clean.describe()

,id,full_sq,kitch_sq,floor,max_floor,area_m,raion_popul,green_zone_part,indust_part,children_preschool,...,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,pop_density,elder_ratio,youth_ratio,floor_ratio,year,month
count,30142.00000,30142.000000,30142.000000,30142.000000,30142.000000,3.014200e+04,30142.000000,30142.000000,30142.000000,30142.000000,...,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000
mean,15276.83737,53.852465,9.927737,7.429865,13.245442,1.761762e+07,84236.673114,0.218597,0.119145,5150.860660,...,9.964648,71.519952,0.291200,16.964993,0.009732,0.225962,0.135966,0.562630,2013.457070,6.745803
std,8789.95339,21.242620,5.960647,5.316839,5.878794,2.056637e+07,57882.834891,0.175095,0.118793,3818.881213,...,4.439491,12.141640,0.149703,5.012847,0.007173,0.036994,0.021070,0.281067,0.961657,3.520572
min,1.00000,10.000000,1.481618,1.000000,1.000000,2.081628e+06,2546.000000,0.001879,0.000000,175.000000,...,4.262096,67.400112,0.220400,10.567959,0.000015,0.114854,0.078007,0.027027,2011.000000,1.000000
25%,7683.25000,38.000000,6.000000,3.000000,9.000000,7.307411e+06,21819.000000,0.063755,0.019509,1706.000000,...,4.262096,67.400112,0.220400,10.567959,0.001750,0.215179,0.123241,0.333333,2013.000000,4.000000
50%,15298.50000,49.000000,8.847859,6.000000,14.000000,1.041657e+07,83502.000000,0.167526,0.072158,4926.000000,...,8.039559,68.573449,0.248999,16.823747,0.010058,0.225870,0.138872,0.583333,2014.000000,6.000000
75%,22882.75000,63.000000,11.470588,11.000000,17.000000,1.803644e+07,122862.000000,0.336177,0.195781,7103.000000,...,14.648207,71.295861,0.257487,20.825967,0.014948,0.255141,0.143464,0.800000,2014.000000,10.000000
max,30473.00000,407.000000,209.000000,44.000000,57.000000,2.060718e+08,247469.000000,0.852923,0.521867,19223.000000,...,14.648207,146.135335,0.717897,27.602766,0.028298,0.320316,0.260695,1.000000,2015.000000,12.000000

In [ ]:
#create year and month columns:

In [25]:
train_clean['year'] = pd.DatetimeIndex(train_clean['timestamp']).year
train_clean['month'] = pd.DatetimeIndex(train_clean['timestamp']).month

In [27]:
test_clean['year'] = pd.DatetimeIndex(test_clean['timestamp']).year
test_clean['month'] = pd.DatetimeIndex(test_clean['timestamp']).month

In [46]:
features = ['id',
 'timestamp',
 'full_sq',
 'floor',
 'max_floor',
 'kitch_sq',
 'product_type',
 'sub_area',
 'metro_min_walk',
 'kindergarten_km',
 'park_km',
 'kremlin_km',
 'oil_chemistry_km',
 'nuclear_reactor_km',
 'big_market_km',
 'market_shop_km',
 'detention_facility_km',
 'public_healthcare_km',
 'university_km',
 'workplaces_km',
 'preschool_km',
 'big_church_km',
 'okurg_district',
 'pop_density',
 'elder_ratio',
 'youth_ratio',
 'floor_ratio',
 'year',
 'month',
 'oil_urals',
 'cpi',
 'eurrub',
 'average_provision_of_build_contract_moscow',
 'micex',
 'mortgage_rate',
 'rent_price_4+room_bus',
 'sd_oil_yearly',
 'sd_cpi_yearly',
 'sd_eurrub_yearly',
 'sd_micex_yearly',
 'sd_mortgage_yearly',
 'sd_rent_yearly',
 'price_doc']

train_trial2 = train_clean[features]

In [47]:
train_trial2.describe()

,id,full_sq,floor,max_floor,kitch_sq,metro_min_walk,kindergarten_km,park_km,kremlin_km,oil_chemistry_km,...,micex,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_eurrub_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,price_doc
count,30142.00000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,...,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,3.014200e+04
mean,15276.83737,53.852465,7.429865,13.245442,9.927737,42.470600,0.981219,3.086617,16.012896,17.365279,...,1464.154910,12.532483,163.360429,9.663918,9.270817,4.332140,71.519952,0.291200,16.964993,7.122612e+06
std,8789.95339,21.242620,5.316839,5.878794,5.960647,68.922730,2.128323,3.942400,8.410187,10.393298,...,98.785541,0.653758,20.469919,4.575206,2.475374,2.659083,12.141640,0.149703,5.012847,4.744716e+06
min,1.00000,10.000000,1.000000,1.000000,1.481618,0.000000,0.000470,0.003737,0.072897,0.510710,...,1237.430000,11.400000,100.080000,3.808905,5.080692,0.767611,67.400112,0.220400,10.567959,1.000000e+05
25%,7683.25000,38.000000,3.000000,9.000000,6.000000,11.447991,0.199337,0.972929,10.460471,8.649078,...,1398.200000,12.220000,149.100000,3.808905,6.802652,1.769683,67.400112,0.220400,10.567959,4.744593e+06
50%,15298.50000,49.000000,6.000000,14.000000,8.847859,20.446384,0.350893,1.804517,14.865596,16.648644,...,1460.930000,12.300000,160.690000,8.009779,10.395346,6.599686,68.573449,0.248999,16.823747,6.287221e+06
75%,22882.75000,63.000000,11.000000,17.000000,11.470588,45.322032,0.971417,3.404787,20.586124,23.424518,...,1502.650000,12.620000,174.220000,14.488195,10.395346,6.599686,71.295861,0.257487,20.825967,8.300000e+06
max,30473.00000,407.000000,44.000000,57.000000,209.000000,711.215806,29.085774,47.351538,70.738769,70.413434,...,1838.180000,14.710000,212.870000,14.488195,14.482090,7.036363,146.135335,0.717897,27.602766,9.512250e+07

In [ ]:
#did not dummify/label encode the okurg_district, sub_area, product_type yet.

In [48]:
train_trial2

,id,timestamp,full_sq,floor,max_floor,kitch_sq,product_type,sub_area,metro_min_walk,kindergarten_km,...,micex,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_eurrub_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,price_doc
0,1,2011-08-20,43,4,5.0,4.962353,Investment,Bibirevo,13.575119,0.145700,...,1438.74,11.84,136.11,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5850000
1,2,2011-08-23,34,3,9.0,5.066667,Investment,Nagatinskij Zaton,7.620630,0.147754,...,1444.11,11.84,136.11,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,6000000
2,3,2011-08-27,43,2,5.0,7.327128,Investment,Tekstil'shhiki,17.351515,0.049102,...,1458.84,11.84,136.11,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5700000
3,4,2011-09-01,89,9,17.0,18.005926,Investment,Mitino,11.565624,0.179441,...,1551.58,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,13100000
4,5,2011-09-05,77,4,8.0,14.016776,Investment,Basmannoe,8.266305,0.247901,...,1492.83,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,16331452
5,6,2011-09-06,67,14,17.0,14.288776,Investment,Nizhegorodskoe,18.378170,0.145955,...,1499.70,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,9100000
6,7,2011-09-08,25,10,12.0,2.863636,Investment,Sokol'niki,12.322993,0.501166,...,1556.46,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5500000
7,8,2011-09-09,44,5,9.0,4.400000,Investment,Bibirevo,11.527788,0.134365,...,1518.22,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,2000000
8,9,2011-09-10,42,5,9.0,6.769811,Investment,Koptevo,14.742289,0.112905,...,1518.22,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5300000
9,10,2011-09-13,36,9,12.0,3.883846,Investment,Kuncevo,4.755297,0.309673,...,1498.16,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,2000000
10,11,2011-09-16,36,12,14.0,6.252632,Investment,Kosino-Uhtomskoe,14.860185,0.175444,...,1511.50,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,4650000
11,12,2011-09-16,38,11,16.0,7.005051,Investment,Zapadnoe Degunino,27.678043,0.341368,...,1511.50,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,4800000
12,13,2011-09-17,43,4,5.0,7.333333,Investment,Kuncevo,19.479949,0.240614,...,1511.50,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5100000
13,14,2011-09-19,31,4,5.0,6.888889,Investment,Presnenskoe,14.576476,0.478112,...,1493.19,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5200000
14,15,2011-09-19,31,3,5.0,5.722387,Investment,Lefortovo,7.081564,0.196604,...,1493.19,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5000000
15,16,2011-09-20,51,15,17.0,8.914195,Investment,Mar'ino,12.542844,0.238081,...,1519.95,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,1850000
16,17,2011-09-20,47,4,5.0,7.380952,Investment,Kuz'minki,7.453252,0.354595,...,1519.95,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,6300000
17,18,2011-09-20,42,2,5.0,6.705426,Investment,Nagornoe,14.134526,0.303114,...,1519.95,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5900000
18,19,2011-09-22,59,10,14.0,11.800000,Investment,Kosino-Uhtomskoe,17.145101,0.161435,...,1389.43,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,7900000
19,20,2011-09-22,44,4,5.0,6.755426,Investment,Gol'janovo,15.912103,0.321336,...,1389.43,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5200000
20,21,2011-09-22,74,10,14.0,9.565217,Investment,Vnukovo,71.554924,0.323308,...,1389.43,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,8200000
21,22,2011-09-22,39,7,14.0,7.383367,Investment,Juzhnoe Tushino,23.469116,0.853442,...,1389.43,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5200000
22,23,2011-09-23,48,6,9.0,7.771429,Investment,Severnoe Tushino,17.881361,0.597949,...,1327.19,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,6250000
23,24,2011-09-23,32,3,9.0,3.772610,Investment,Chertanovo Central'noe,0.687058,0.166564,...,1327.19,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5750000
24,25,2011-09-23,34,11,12.0,4.432707,Investment,Juzhnoe Tushino,30.656268,0.145299,...,1327.19,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,6000000
25,26,2011-09-24,45,9,12.0,6.674603,Investment,Fili Davydkovo,14.500328,0.354140,...,1327.19,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,1050000
26,27,2011-09-26,35,4,9.0,4.782609,Investment,Otradnoe,12.266605,0.277521,...,1346.86,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5000000
27,28,2011-09-26,38,6,9.0,6.666667,Investment,Novo-Peredelkino,13.119129,0.409804,...,1346.86,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,4700000
28,29,2011-09-26,73,15,17.0,9.500000,OwnerOccupier,Bogorodskoe,11.302103,0.074910,...,1346.86,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,8254400
29,30,2011-09-27,42,3,5.0,8.364833,Investment,Jaroslavskoe,29.819246,0.397870,...,1380.42,11.92,155.22,6.269592,5.080692,1.085887,146.135335,0.361158,16.374863,5900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30137,30444,2015-06-27,113,26,26.0,24.483333,OwnerOccupier,Tverskoe,13.459068,1.048962,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,25039300
30138,30445,2015-06-27,40,2,12.0,10.000000,OwnerOccupier,Poselenie Voskresenskoe,29.242588,0.745286,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,4350000
30139,30446,2015-06-27,79,17,17.0,14.596154,OwnerOccupier,Solncevo,24.450869,0.230087,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,7567425
30140,30447,2015-06-27,85,20,25.0,18.346657,OwnerOccupier,Mitino,11.322397,0.958374,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,11438948
30141,30448,2015-06-27,47,19,25.0,10.000000,OwnerOccupier,Filevskij Park,25.004226,0.726512,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,10139368
30142,30449,2015-06-27,82,8,8.0,25.033333,OwnerOccupier,Poselenie Sosenskoe,71.012576,3.829123,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6125400
30143,30450,2015-06-27,64,15,17.0,11.824732,OwnerOccupier,Solncevo,24.450869,0.230087,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6373324
30144,30451,2015-06-27,74,8,17.0,21.764706,OwnerOccupier,Poselenie Moskovskij,68.402944,3.861878,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6888144
30145,30452,2015-06-27,47,7,25.0,10.000000,OwnerOccupier,Filevskij Park,25.004226,0.726512,...,1644.45,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,9227657
30146,30453,2015-06-29,65,5,7.0,9.067029,OwnerOccupier,Otradnoe,19.924755,0.092937,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,12610000
30147,30454,2015-06-29,37,3,3.0,10.882353,OwnerOccupier,Poselenie Novofedorovskoe,534.645955,23.526686,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,2394300
30148,30455,2015-06-29,38,7,17.0,7.000000,Investment,Ochakovo-Matveevskoe,45.339596,0.463896,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6800000
30149,30456,2015-06-29,45,6,15.0,8.458647,OwnerOccupier,Juzhnoe Butovo,19.251380,0.727786,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,4066740
30150,30457,2015-06-29,40,3,9.0,5.000000,Investment,Bogorodskoe,14.842129,0.082434,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6300000
30151,30458,2015-06-29,79,3,3.0,14.566742,OwnerOccupier,Poselenie Vnukovskoe,24.925384,1.170413,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,9014972
30152,30459,2015-06-29,52,8,14.0,8.000000,Investment,Mitino,8.350721,0.621263,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,1000000
30153,30460,2015-06-29,58,7,9.0,6.000000,Investment,Jaroslavskoe,84.480123,0.123436,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,7800000
30154,30461,2015-06-29,50,7,7.0,11.434783,OwnerOccupier,Poselenie Moskovskij,21.368381,1.075395,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6370777
30155,30462,2015-06-29,51,4,17.0,9.422833,OwnerOccupier,Solncevo,24.450869,0.230087,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,5778893
30156,30463,2015-06-29,54,8,16.0,9.000000,Investment,Jasenevo,14.473533,0.332310,...,1634.93,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,9500000
30157,30464,2015-06-30,36,5,16.0,8.000000,Investment,Obruchevskoe,17.619417,0.417062,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,5000000
30158,30465,2015-06-30,47,23,25.0,10.000000,OwnerOccupier,Filevskij Park,25.004226,0.726512,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,10544070
30159,30466,2015-06-30,56,13,14.0,11.000000,Investment,Severnoe Tushino,8.510351,0.225720,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,12000000
30160,30467,2015-06-30,56,19,19.0,9.953488,OwnerOccupier,Sviblovo,7.447930,0.414927,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,10262010
30161,30468,2015-06-30,52,13,17.0,11.266667,OwnerOccupier,Tverskoe,13.459068,1.048962,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6750554
30162,30469,2015-06-30,44,7,9.0,6.000000,Investment,Otradnoe,8.158093,0.132645,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,7400000
30163,30470,2015-06-30,86,3,9.0,10.000000,Investment,Tverskoe,9.374609,0.276256,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,25000000
30164,30471,2015-06-30,45,10,20.0,8.766603,OwnerOccupier,Poselenie Vnukovskoe,20.666800,0.897889,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,6970959
30165,30472,2015-06-30,64,5,15.0,11.000000,Investment,Obruchevskoe,24.567748,0.203020,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,13500000
30166,30473,2015-06-30,43,1,9.0,6.000000,Investment,Novogireevo,5.455795,0.093619,...,1654.55,13.46,167.37,8.009779,14.482090,7.036363,71.295861,0.717897,27.602766,5600000

In [49]:
train_trial2.to_csv('trial_brandy2.csv', index = False)

# Final Test data to grant (chase imputed)

In [60]:
#import data and merge the macro onto the train and test
testvsm_df = pd.read_csv("test_vsmall.csv", parse_dates=['timestamp'])
macrosm_df = pd.read_csv("macro_small.csv", parse_dates=['timestamp'])
okurg_df = pd.read_csv("okurg.csv")
chase_test = pd.read_csv("chase_final_test.csv")

In [61]:
testvsm_df.describe()
#chase_test.describe()

,id,area_m,raion_popul,young_all,work_all,ekder_all,metro_min_walk,kindergarten_km,park_km,oil_chemistry_km,nuclear_reactor_km,big_market_km,market_shop_km,detention_facility_km,public_healthcare_km,university_km,workplaces_km,preschool_km,big_church_km,kremlin_km
count,7662.000000,7.662000e+03,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000
mean,34304.500000,1.768576e+07,87522.520882,11637.004046,55893.865570,19991.651266,42.204950,1.103444,2.925088,18.083807,10.474130,13.442552,3.852978,14.580870,3.311623,6.695523,4.061873,1.461588,2.285456,15.440871
std,2211.973214,2.210728e+07,56306.189481,8152.046915,36501.517268,12764.084918,76.380618,2.781981,3.707211,10.647041,7.753394,8.376569,3.591212,11.261294,4.441946,6.995094,5.616999,3.526377,3.192405,8.694792
min,30474.000000,2.081628e+06,2546.000000,365.000000,1633.000000,548.000000,0.086598,0.001000,0.015875,0.573143,0.377167,0.705571,0.029552,0.151575,0.013736,0.002820,0.060500,0.032218,0.004208,0.072897
25%,32389.250000,7.307411e+06,37502.000000,5238.000000,22573.000000,8935.000000,11.368367,0.204924,0.928846,8.990952,4.685959,7.836658,1.533536,5.286908,1.242741,2.160815,0.955159,0.306963,0.803070,9.551782
50%,34304.500000,1.005305e+07,85956.000000,11272.000000,54914.000000,20247.000000,19.049978,0.389760,1.644467,17.055745,8.004229,12.132460,2.820438,11.213928,2.084625,3.960500,1.890520,0.549211,1.353545,14.096756
75%,36219.750000,1.788191e+07,118945.000000,15727.000000,76776.000000,29431.000000,35.730206,0.944998,3.101220,23.878374,15.300988,17.030740,5.417379,23.355154,3.502832,9.025801,5.247596,0.980645,2.552608,20.092917
max,38135.000000,2.060718e+08,247469.000000,40692.000000,161290.000000,57086.000000,699.158482,27.453271,47.351538,70.413434,64.256957,58.830654,41.103651,89.371374,76.055135,84.862148,55.278225,47.394706,45.669060,70.738769

In [62]:
testvsm_df = pd.merge(testvsm_df, macrosm_df, how='left', on='timestamp')
testvsm_df = pd.merge(testvsm_df, okurg_df, how='left', on='sub_area')
test_chase = pd.merge(testvsm_df, chase_test, how='left', on='id')

In [63]:
test_chase.describe()

,id,area_m,raion_popul,young_all,work_all,ekder_all,metro_min_walk,kindergarten_km,park_km,oil_chemistry_km,...,sd_cpi_yearly,sd_ppi_yearly,sd_eurrub_yearly,sd_brent_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,full_sq,floor,max_floor
count,7662.000000,7.662000e+03,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,...,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000
mean,34304.500000,1.768576e+07,87522.520882,11637.004046,55893.865570,19991.651266,42.204950,1.103444,2.925088,18.083807,...,10.357489,21.469072,6.039786,7.231745,81.374219,0.484803,29.842628,53.685461,7.218220,13.455051
std,2211.973214,2.210728e+07,56306.189481,8152.046915,36501.517268,12764.084918,76.380618,2.781981,3.707211,10.647041,...,3.964332,2.790806,0.957853,0.776425,9.686745,0.224037,2.152828,19.682836,5.130323,5.907057
min,30474.000000,2.081628e+06,2546.000000,365.000000,1633.000000,548.000000,0.086598,0.001000,0.015875,0.573143,...,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766,10.000000,1.000000,1.000000
25%,32389.250000,7.307411e+06,37502.000000,5238.000000,22573.000000,8935.000000,11.368367,0.204924,0.928846,8.990952,...,6.547696,18.787058,5.119272,6.485588,71.295861,0.269500,27.602766,39.200000,3.000000,9.000000
50%,34304.500000,1.005305e+07,85956.000000,11272.000000,54914.000000,20247.000000,19.049978,0.389760,1.644467,17.055745,...,6.547696,18.787058,5.119272,6.485588,90.683353,0.269500,31.911534,50.420000,6.000000,14.000000
75%,36219.750000,1.788191e+07,118945.000000,15727.000000,76776.000000,29431.000000,35.730206,0.944998,3.101220,23.878374,...,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534,63.300000,10.000000,17.000000
max,38135.000000,2.060718e+08,247469.000000,40692.000000,161290.000000,57086.000000,699.158482,27.453271,47.351538,70.413434,...,14.482090,24.372704,7.036363,8.039559,90.683353,0.717897,31.911534,314.500000,41.000000,48.000000

Add features:

In [64]:
#pull out year and month
test_chase['year'] = pd.DatetimeIndex(test_chase['timestamp']).year
test_chase['month'] = pd.DatetimeIndex(test_chase['timestamp']).month

In [65]:
#floor to max floor ratio
test_chase["floor_ratio"] = test_chase["floor"] / test_chase["max_floor"].astype("float")

In [66]:
#Ratio of elder population (will be the same throughout each SubArea)
test_chase["elder_ratio"] = test_chase["ekder_all"] / (test_chase["young_all"] + test_chase["work_all"] + test_chase["ekder_all"]).astype("float")

#Ratio of under 18 population (will be the same throughout each SubArea)
test_chase["youth_ratio"] = test_chase["young_all"] / (test_chase["young_all"] + test_chase["work_all"] + test_chase["ekder_all"]).astype("float")

#Population Density (will be the same throughout each SubArea)
test_chase["pop_density"] = test_chase["raion_popul"] / test_chase["area_m"].astype("float")

In [67]:
features_test = ['id',
 'timestamp',
 'full_sq',
 'floor',
 'max_floor',
 'product_type',
 'sub_area',
 'metro_min_walk',
 'kindergarten_km',
 'park_km',
 'kremlin_km',
 'oil_chemistry_km',
 'nuclear_reactor_km',
 'big_market_km',
 'market_shop_km',
 'detention_facility_km',
 'public_healthcare_km',
 'university_km',
 'workplaces_km',
 'preschool_km',
 'big_church_km',
 'okurg_district',
 'pop_density',
 'elder_ratio',
 'youth_ratio',
 'floor_ratio',
 'year',
 'month',
 'oil_urals',
 'cpi',
 'eurrub',
 'average_provision_of_build_contract_moscow',
 'micex',
 'mortgage_rate',
 'rent_price_4+room_bus',
 'sd_oil_yearly',
 'sd_cpi_yearly',
 'sd_eurrub_yearly',
 'sd_micex_yearly',
 'sd_mortgage_yearly',
 'sd_rent_yearly']

test_final = test_chase[features_test]

In [68]:
test_final.describe()

,id,full_sq,floor,max_floor,metro_min_walk,kindergarten_km,park_km,kremlin_km,oil_chemistry_km,nuclear_reactor_km,...,average_provision_of_build_contract_moscow,micex,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_eurrub_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly
count,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,...,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000,7662.000000
mean,34304.500000,53.685461,7.218220,13.455051,42.204950,1.103444,2.925088,15.440871,18.083807,10.474130,...,6.872287,1764.953297,12.726691,181.616325,6.960293,10.357489,6.039786,81.374219,0.484803,29.842628
std,2211.973214,19.682836,5.130323,5.907057,76.380618,2.781981,3.707211,8.694792,10.647041,7.753394,...,0.249751,88.642509,0.394161,28.196758,1.008706,3.964332,0.957853,9.686745,0.224037,2.152828
min,30474.000000,10.000000,1.000000,1.000000,0.086598,0.001000,0.015875,0.072897,0.573143,0.377167,...,6.220000,1584.920000,12.100000,142.850000,5.990909,6.547696,5.119272,71.295861,0.269500,27.602766
25%,32389.250000,39.200000,3.000000,9.000000,11.368367,0.204924,0.928846,9.551782,8.990952,4.685959,...,6.900000,1710.570000,12.290000,164.260000,5.990909,6.547696,5.119272,71.295861,0.269500,27.602766
50%,34304.500000,50.420000,6.000000,14.000000,19.049978,0.389760,1.644467,14.096756,17.055745,8.004229,...,6.920000,1746.350000,12.860000,174.650000,5.990909,6.547696,5.119272,90.683353,0.269500,31.911534
75%,36219.750000,63.300000,10.000000,17.000000,35.730206,0.944998,3.101220,20.092917,23.878374,15.300988,...,6.920000,1840.170000,12.920000,205.640000,8.009779,14.482090,7.036363,90.683353,0.717897,31.911534
max,38135.000000,314.500000,41.000000,48.000000,699.158482,27.453271,47.351538,70.738769,70.413434,64.256957,...,7.120000,1969.890000,13.440000,242.230000,8.009779,14.482090,7.036363,90.683353,0.717897,31.911534

In [69]:
test_final.to_csv('test_final.csv', index = False)

In [ ]:
#did not dummify/label encode the okurg_district, sub_area, product_type yet.

In [70]:
train_1 = pd.read_csv("trial_brandy2.csv", parse_dates=['timestamp'])
train_2 = pd.read_csv("train_final.csv", parse_dates=['timestamp'])

In [71]:
train_1.describe()

,id,full_sq,floor,max_floor,metro_min_walk,kindergarten_km,park_km,kremlin_km,oil_chemistry_km,nuclear_reactor_km,...,micex,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_eurrub_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,price_doc
count,30142.00000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,...,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,3.014200e+04
mean,15276.83737,53.852465,7.429865,13.245442,42.470603,0.981219,3.086617,16.012896,17.365279,10.918128,...,1464.154910,12.532483,163.360429,9.663918,9.270817,4.332140,71.519952,0.291200,16.964993,7.122612e+06
std,8789.95339,21.242620,5.316839,5.878794,68.922729,2.128323,3.942400,8.410187,10.393298,7.217586,...,98.785541,0.653758,20.469919,4.575206,2.475374,2.659083,12.141640,0.149703,5.012847,4.744716e+06
min,1.00000,10.000000,1.000000,1.000000,0.080000,0.000470,0.003737,0.072897,0.510710,0.309811,...,1237.430000,11.400000,100.080000,3.808905,5.080692,0.767611,67.400112,0.220400,10.567959,1.000000e+05
25%,7683.25000,38.000000,3.000000,9.000000,11.447991,0.199337,0.972929,10.460471,8.649078,5.230867,...,1398.200000,12.220000,149.100000,3.808905,6.802652,1.769683,67.400112,0.220400,10.567959,4.744593e+06
50%,15298.50000,49.000000,6.000000,14.000000,20.446384,0.350893,1.804517,14.865596,16.648644,8.957687,...,1460.930000,12.300000,160.690000,8.009779,10.395346,6.599686,68.573449,0.248999,16.823747,6.287221e+06
75%,22882.75000,63.000000,11.000000,17.000000,45.322032,0.971417,3.404787,20.586124,23.424518,16.372510,...,1502.650000,12.620000,174.220000,14.488195,10.395346,6.599686,71.295861,0.257487,20.825967,8.300000e+06
max,30473.00000,407.000000,44.000000,57.000000,711.215806,29.085774,47.351538,70.738769,70.413434,64.256957,...,1838.180000,14.710000,212.870000,14.488195,14.482090,7.036363,146.135335,0.717897,27.602766,9.512250e+07

In [72]:
train_2.describe()

,id,full_sq,floor,max_floor,metro_min_walk,kindergarten_km,park_km,kremlin_km,oil_chemistry_km,nuclear_reactor_km,...,micex,mortgage_rate,rent_price_4+room_bus,sd_oil_yearly,sd_cpi_yearly,sd_eurrub_yearly,sd_micex_yearly,sd_mortgage_yearly,sd_rent_yearly,price_doc
count,30142.00000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,...,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,30142.000000,3.014200e+04
mean,15276.83737,53.852465,7.429865,13.245442,42.470603,0.981219,3.086617,16.012896,17.365279,10.918128,...,1464.154910,12.532483,163.360429,9.663918,9.270817,4.332140,71.519952,0.291200,16.964993,7.122612e+06
std,8789.95339,21.242620,5.316839,5.878794,68.922729,2.128323,3.942400,8.410187,10.393298,7.217586,...,98.785541,0.653758,20.469919,4.575206,2.475374,2.659083,12.141640,0.149703,5.012847,4.744716e+06
min,1.00000,10.000000,1.000000,1.000000,0.080000,0.000470,0.003737,0.072897,0.510710,0.309811,...,1237.430000,11.400000,100.080000,3.808905,5.080692,0.767611,67.400112,0.220400,10.567959,1.000000e+05
25%,7683.25000,38.000000,3.000000,9.000000,11.447991,0.199337,0.972929,10.460471,8.649078,5.230867,...,1398.200000,12.220000,149.100000,3.808905,6.802652,1.769683,67.400112,0.220400,10.567959,4.744593e+06
50%,15298.50000,49.000000,6.000000,14.000000,20.446384,0.350893,1.804517,14.865596,16.648644,8.957687,...,1460.930000,12.300000,160.690000,8.009779,10.395346,6.599686,68.573449,0.248999,16.823747,6.287221e+06
75%,22882.75000,63.000000,11.000000,17.000000,45.322032,0.971417,3.404787,20.586124,23.424518,16.372510,...,1502.650000,12.620000,174.220000,14.488195,10.395346,6.599686,71.295861,0.257487,20.825967,8.300000e+06
max,30473.00000,407.000000,44.000000,57.000000,711.215806,29.085774,47.351538,70.738769,70.413434,64.256957,...,1838.180000,14.710000,212.870000,14.488195,14.482090,7.036363,146.135335,0.717897,27.602766,9.512250e+07