In [69]:
import pandas as pd
import numpy as np
import re

In [253]:
oed = pd.read_csv('oed_3.csv')
print oed.shape
oed.head()

(3470, 5)

       entry_type  year  part_of_speech          word      month
0  new word entry  2014             n.4          case  September
1  new word entry  2014   adv. and adj.  case-by-case  September
2  new word entry  2014           adj.2      caseless  September
3  new word entry  2014              n.      caseness  September
4  new word entry  2014             n.1    caseworker  September

In [254]:
oed['entry_type']=oed['entry_type'].map(str)
oed['word']=oed['word'].map(str)
oed['month']=oed['month'].map(str)
oed['year']=oed['year'].map(str)
oed['part_of_speech']=oed['part_of_speech'].map(str)

In [255]:
oed['acronym'] = oed['word'].map(lambda x: x==x.upper())
oed[oed['acronym']==True]

          entry_type  year    part_of_speech    word      month acronym
1199  new word entry  2015                n.  FLOTUS       June    True
1223  new word entry  2015                n.     H2O       June    True
1270  new word entry  2015   int. (and adj.)     KKB       June    True
1317  new word entry  2015                n.    SCBU       June    True
1323  new word entry  2015                n.  SCOTUS       June    True
1503   new sub-entry  2015                n.  FLOTUS       June    True
1527  new word entry  2015               n.2     ISA  September    True
1540   new sub-entry  2015                n.     H2O       June    True
1592   new sub-entry  2015               n.2     ISA  September    True
1637   new sub-entry  2015   int. (and adj.)     KKB       June    True
1666  new word sense  2015               n.2     ISA  September    True
1720   new sub-entry  2015                n.    SCBU       June    True
1726   new sub-entry  2015                n.  SCOTUS       June    True
2021  new word sense  2015                n.  FLOTUS       June    True
2064  new word sense  2015                n.     H2O       June    True
2111  new word sense  2015   int. (and adj.)     KKB       June    True
2196  new word sense  2015                n.    SCBU       June    True
2202  new word sense  2015                n.  SCOTUS       June    True
2959  new word entry  2017                n.     420      March    True
3196   new sub-entry  2017                n.     420      March    True
3333  new word sense  2017                n.     420      March    True

In [256]:
oed['dash'] =oed['word'].map(lambda x: re.search('-', x.lower()) != None)
oed['dash'].value_counts()

np.unique(oed[oed['dash']==True]['word'])

array(['-going', '-kine', 'A-rab', 'Belgo-', 'Blu-ray', 'Can-Am',
       'Canadian-American', 'Chi-town', 'Hardy-Weinberg', 'adults-only',
       'anti-unionism', 'bank-switch', 'bank-switched', 'better-heeled',
       'better-paid', 'bluff-charge', 'bluff-charging', 'bug-eyes',
       'bug-out', 'buggered-up', 'case-by-case', 'class-ified', 'dial-in',
       'double-double', 'drink-driver', 'e-cig', 'e-cigarette',
       'e-edition', 'e-skin', 'e-toll', 'ear-grass', 'ear-opening',
       'ear-piercing', 'ear-popping', 'ear-tag', 'ear-tickler',
       'ear-to-ear', 'eye-popping', 'eye-roll', 'eye-roller',
       'eye-rolling', 'eyebrow-raiser', 'eyebrow-raising', 'fact-check',
       'fact-checker', 'fact-checking', 'fair-traded', 'family-style',
       'feed-in', 'fire-bombed', 'fire-setting', 'first-handed',
       'go-for-broke', 'go-for-it', 'go-harvest', 'go-juice',
       'going-about', 'good-enough Morgan', 'grow-op', 'half-ass',
       'halo-halo', 'happy-slappy', 'hard-arse', 'hard-arsed',
       'hard-bodied', 'hard-code', 'hard-coded', 'havey-cavey',
       'high muckety-muck', 'high-centre | high-center',
       'high-centred | high-centered', 'high-centring | high-centering',
       'high-fiving', 'high-full', 'high-graded', 'high-living',
       'high-rider', 'high-riding', 'high-rolling', 'high-stick',
       'hip-hopping', 'house-made', 'large-cap', 'lock-stitched',
       'lock-upable', 'look-see', 'lookie-likie', 'low-balling',
       'low-bridge', 'low-lifer', 'low-maintenance', 'low-rate',
       'low-riding', 'low-top', 'mangia-cake', 'merry-go-around',
       'mini-stroke', 'off-grid', 'old-earth', 'on-trend', 'ooh-wee',
       'sari-sari store', 'say-away', 'scent-mark', 'self-immolate',
       'smash-mouth', 'stick-to-itness', 'sticky-outy', 'stir-fry',
       'stuck-in-the-mud', 'take-back', 'they-all', 'to-go', 'top-rope',
       'tow-netting', 'trade-name', 'trade-up', 'tragico-comedy',
       'tragico-comic', 'tragico-comical', 'uber-', 'un-PC',
       'under-strength', 'water-cycle', 'water-repellence',
       'well-administered', 'well-advanced', 'well-engineered',
       'well-ground', 'well-iqueme', 'well-justified', 'well-observed',
       'well-occupied', 'well-operated', 'well-paced', 'well-paying',
       'well-populated', 'well-positioned', 'well-pressed',
       'well-produced', 'well-provided-for', 'well-rewarded',
       'well-sorted', 'well-supported', 'well-treated', 'white-chinned',
       'white-clawed', 'young-earth'], dtype=object)

In [257]:
oed['word_length'] = oed['word'].map(lambda x: len(str(x).split(' ')))
oed.head()

,entry_type,year,part_of_speech,word,month,acronym,dash,word_length
0,new word entry,2014,n.4,case,September,False,False,1
1,new word entry,2014,adv. and adj.,case-by-case,September,False,True,1
2,new word entry,2014,adj.2,caseless,September,False,False,1
3,new word entry,2014,n.,caseness,September,False,False,1
4,new word entry,2014,n.1,caseworker,September,False,False,1

In [258]:
oed['word_length'].value_counts()

1    2865
2     517
3      79
5       6
4       3
Name: word_length, dtype: int64

In [259]:
oed.sort_values('word_length', ascending=False)

,entry_type,year,part_of_speech,word,month,acronym,dash,word_length
184,new word sense,2014,n.,high centre | high center,September,False,False,5
28,new word entry,2014,n.,high centre | high center,September,False,False,5
455,new sub-entry,2013,n.,grey zone | gray zone,September,False,False,5
541,new word sense,2013,n.,grey zone | gray zone,September,False,False,5
369,new word entry,2013,n.,grey zone | gray zone,September,False,False,5
106,new sub-entry,2014,n.,high centre | high center,September,False,False,5
1000,new word sense,2014,n. and phr.,dulce et decorum est,June,False,False,4
829,new sub-entry,2014,n. and phr.,dulce et decorum est,June,False,False,4
658,new word entry,2014,n. and phr.,dulce et decorum est,June,False,False,4
488,new sub-entry,2013,adj.,non se ipse,September,False,False,3
264,new word entry,2015,n.,Whites tree frog,March,False,False,3
1788,new sub-entry,2015,n.,utang na loob,June,False,False,3
1787,new word entry,2013,adj. (and adv.),la bourgeoise,December,False,False,3
659,new word entry,2014,n.,dulce et decorum,June,False,False,3
118,new sub-entry,2014,n.,high-centring | high-centering,September,False,True,3
117,new sub-entry,2014,adj.,high-centred | high-centered,September,False,True,3
3311,new sub-entry,2017,n. and adj.,South African English,March,False,False,3
116,new sub-entry,2014,v.,high-centre | high-center,September,False,True,3
1556,new sub-entry,2015,int. (and n.),har de har,June,False,False,3
1713,new word sense,2015,n.,watercolouring | watercoloring,September,False,False,3
297,new sub-entry,2015,n.,Whites tree frog,March,False,False,3
1679,new sub-entry,2015,n.,pan de sal,June,False,False,3
2151,new word sense,2015,n.,pan de sal,June,False,False,3
3174,new word entry,2017,n. and adj.,South African English,March,False,False,3
1955,new word entry,2013,n.,embarras de choix,December,False,False,3
76,new word entry,2014,adv. and adj.,year over year,September,False,False,3
1497,new sub-entry,2015,int.,fap fap fap,June,False,False,3
2591,new word entry,2014,n.,good King Henry,December,False,False,3
415,new word entry,2013,adv.,top to tail,September,False,False,3
67,new word entry,2014,adv. and adj.,week by week,September,False,False,3
...,...,...,...,...,...,...,...,...
1314,new word entry,2015,n.,sanger,June,False,False,1
1316,new word entry,2015,n.,say-away,June,False,True,1
1317,new word entry,2015,n.,SCBU,June,True,False,1
1318,new word entry,2015,n.,scenarioist,June,False,False,1
1319,new word entry,2015,v.,scene,June,False,False,1
1298,new word entry,2015,n.,pharmacovigilance,June,False,False,1
1296,new word entry,2015,n.,papsak,June,False,False,1
1271,new word entry,2015,n.,koozie,June,False,False,1
1282,new word entry,2015,n.,merry-go-around,June,False,True,1
1272,new word entry,2015,n.,kryptonite,June,False,False,1
1273,new word entry,2015,n.,kuya,June,False,False,1
1274,new word entry,2015,n.2,lede,June,False,False,1
1275,new word entry,2015,int.,mabuhay,June,False,False,1
1276,new word entry,2015,adv. and adj.,mahala,June,False,False,1
1277,new word entry,2015,n.,Mamil,June,False,False,1
1278,new word entry,2015,n.,mangia-cake,June,False,True,1
1280,new word entry,2015,n.,Masshole,June,False,False,1
1281,new word entry,2015,int. and adj.,meh,June,False,False,1
1283,new word entry,2015,n.,mini-stroke,June,False,True,1
1294,new word entry,2015,n.,pageview,June,False,False,1
1284,new word entry,2015,n.,Morgellons,June,False,False,1
1285,new word entry,2015,n.,nanodiamond,June,False,False,1
1286,new word entry,2015,adj.,nanosized,June,False,False,1
1287,new word entry,2015,n.2,netbook,June,False,False,1
1289,new word entry,2015,adj. and adv.,off-grid,June,False,True,1
1290,new word entry,2015,adj.,old-earth,June,False,True,1
1291,new word entry,2015,v.,onsight,June,False,False,1
1292,new word entry,2015,adj. and adv.,on-trend,June,False,True,1
1293,new word entry,2015,n.,oophagy,June,False,False,1
3469,new word sense,2017,comb._form3,-kine,March,False,True,1

In [260]:
cw = pd.read_csv('cw_full.csv').drop('Unnamed: 0', axis=1)

print(cw.shape)
cw.head()

(128101, 8)

,title,clue,date,year,answer,unique,day,answer_count
0,,"___ Nast, publisher of Vogue",December 16,2016,CONDE,False,Friday,3
1,,Baby,December 16,2016,SPOIL,False,Friday,4
2,,Voodoo doll action,December 16,2016,HEX,False,Friday,6
3,,"""Robin ___"" (old Irish ballad)",December 16,2016,ADAIR,False,Friday,4
4,,Bittersweet spread,December 16,2016,MARMALADE,False,Friday,1

In [278]:
oed['word'] = oed['word'].map(lambda x: x.lower())
cw['answer'] = cw['answer'].map(lambda x: x.lower())

cw_unique = cw[cw['unique'] == True]
cw_unique['answer'].isin(['brexit']).any()

cw_unique

,title,clue,date,year,answer,unique,day,answer_count
5,,Company concerned with net profits?,December 16,2016,serviceprovider,True,Friday,1
14,,"Server of pink champagne on ice, in song",December 16,2016,hotelcalifornia,True,Friday,1
15,,Is perfectly punctual,December 16,2016,arrivesonthedot,True,Friday,1
17,,Workshop,December 16,2016,trainingseminar,True,Friday,1
41,,"""Rent"" showstopper",December 16,2016,lavieboheme,True,Friday,1
50,,Olden,December 16,2016,ofthepast,True,Friday,1
61,,"""___ Please, We're British"" (1971 stage farce)",December 16,2016,nosex,True,Friday,1
89,,"""Young 'uns, yer cuzzins are here"" and others?",December 8,2016,paannouncements,True,Thursday,1
101,,What Stephen King's editor provided for a 1986...,December 8,2016,itsupport,True,Thursday,1
153,,"Player of Molly on ""Mike &amp; Molly""",December 9,2016,melissamccarthy,True,Friday,1
159,,Received high marks,December 9,2016,gotas,True,Friday,1
171,,Where Roger Ebert's reviews appeared for 47 years,December 9,2016,chicagosuntimes,True,Friday,1
181,,"___ Mayer, Yahoo C.E.O. beginning in 2012",December 9,2016,marissa,True,Friday,1
192,,Pair on Mississippi's state quarter,December 9,2016,magnolias,True,Friday,1
217,,"Bombing, as a joke",December 15,2016,fallingflat,True,Thursday,1
229,,Discriminatory part of post-Reconstruction leg...,December 15,2016,grandfatherclause,True,Thursday,1
235,,Short-stemmed vessel,December 15,2016,parfaitglass,True,Thursday,1
257,,Joe Six-Pack,December 15,2016,regularguy,True,Thursday,1
306,,*One of a dozen for a sweetheart,December 7,2016,cutrose,True,Wednesday,1
313,,*Something to make up,December 7,2016,lostground,True,Wednesday,1
333,,Some street scenes,December 7,2016,urbanart,True,Wednesday,1
334,,Spy communication spots,December 7,2016,deaddrops,True,Wednesday,1
347,,Blows the whistle,December 7,2016,stopsplay,True,Wednesday,1
351,,Working diligently,December 7,2016,hardatit,True,Wednesday,1
392,,"Following the shaded squares, the end to a sea...",December 6,2016,meandmydrum,True,Tuesday,1
412,,"Mr. ___ of ""The Karate Kid""",December 6,2016,miyagi,True,Tuesday,1
455,,It grabs one's attention,December 5,2016,necksnapper,True,Monday,1
461,,Boastful sort,December 5,2016,chestbeater,True,Monday,1
490,,"Keyboard, monitor, mouse and other devices",December 5,2016,peripherals,True,Monday,1
505,,Invitation to a questioner,December 5,2016,askaway,True,Monday,2
...,...,...,...,...,...,...,...,...
127691,,See 40-Across,August 7,2012,notfollowingyou,True,Tuesday,1
127707,,Use a whisk on,August 7,2012,handmix,True,Tuesday,1
127723,,Didn't compromise,August 7,2012,stoodfast,True,Tuesday,1
127727,,Hunk on display,August 7,2012,gqmodel,True,Tuesday,1
127755,,Massage message?,August 10,2012,thatfeelssogood,True,Friday,1
127758,,Sent some cybernotes,August 10,2012,imed,True,Friday,4
127779,,Instant-book title of 1981 or 2011,August 10,2012,theroyalwedding,True,Friday,1
127827,,*Result of a financial panic,August 6,2012,bankrun,True,Monday,1
127828,,*Tight braid,August 6,2012,cornrow,True,Monday,1
127840,,*Precipitous drop in cost,August 6,2012,pricedive,True,Monday,1
127867,,Detects like a bloodhound,August 6,2012,sniffsout,True,Monday,1
127895,SINGLE-MINDED,"Disappointing ""Who's with me?"" response?",August 5,2012,showofhand,True,Sunday,1
127896,SINGLE-MINDED,Work to maintain a C average?,August 5,2012,hitthebook,True,Sunday,1
127900,SINGLE-MINDED,Mention that you know a secret?,August 5,2012,spillthebean,True,Sunday,1
127908,SINGLE-MINDED,One who's read an encyclopedia's first volume?,August 5,2012,manofletter,True,Sunday,1
127912,SINGLE-MINDED,Podunk's directory?,August 5,2012,yellowpage,True,Sunday,1
127919,SINGLE-MINDED,Having finished just one month of a job?,August 5,2012,wetbehindtheear,True,Sunday,1
127926,SINGLE-MINDED,What one with a small nest egg enjoys?,August 5,2012,goldenyear,True,Sunday,1
127930,SINGLE-MINDED,Despot's concession?,August 5,2012,billofright,True,Sunday,1
127938,SINGLE-MINDED,Occasional klutz?,August 5,2012,butterfinger,True,Sunday,1
127942,SINGLE-MINDED,Beginning magician's arsenal?,August 5,2012,bagoftrick,True,Sunday,1
127943,SINGLE-MINDED,Go on a brief youthful binge?,August 5,2012,sowonesoat,True,Sunday,1
127980,SINGLE-MINDED,"""Happens sometimes""",August 5,2012,itcan,True,Sunday,1
128009,SINGLE-MINDED,Cheers on,August 5,2012,rootsfor,True,Sunday,1
128060,,Handle online,August 9,2012,screenname,True,Thursday,1
128073,,Society add-ons,August 9,2012,debutantes,True,Thursday,1
128082,,1984 U.S. Olympic gold medalist in gymnastics,August 9,2012,bartconner,True,Thursday,1
128086,,"""Fame"" actress",August 9,2012,niapeeples,True,Thursday,1
128090,,"""You betcha!""",August 9,2012,yesindeedy,True,Thursday,1
128095,,Roman 112,August 9,2012,cxii,True,Thursday,1

In [262]:

common_words = set(oed['word']).intersection(cw['answer'])
print(len(common_words))
common_words

77

{'arr',
 'autotune',
 'beauty',
 'best',
 'buff',
 'bugs',
 'burgess',
 'carnap',
 'case',
 'catty',
 'chi',
 'chica',
 'cis',
 'commit',
 'coot',
 'dap',
 'dayton',
 'disc',
 'disco',
 'earworm',
 'elegant',
 'emoji',
 'eris',
 'fava',
 'flexagon',
 'gday',
 'gram',
 'gramps',
 'grams',
 'guac',
 'h2o',
 'hap',
 'hash',
 'hatter',
 'he',
 'heal',
 'hex',
 'his',
 'hoverboard',
 'ile',
 'isa',
 'javascript',
 'lac',
 'lasting',
 'lede',
 'locavore',
 'meh',
 'netbook',
 'osha',
 'penna',
 'photobomb',
 'queso',
 'resounded',
 'rested',
 'retweet',
 'sanger',
 'scene',
 'selfie',
 'sext',
 'ship',
 'skort',
 'skype',
 'sledge',
 'staycation',
 'storyboard',
 'structural',
 'stylo',
 'telly',
 'termite',
 'totes',
 'truly',
 'twerk',
 'unobtainium',
 'vape',
 'weekdays',
 'whit',
 'wuss'}

In [263]:
cw[cw['answer']=='sext']

,title,clue,date,year,answer,unique,day,answer_count
939,,Suggestive transmission,May 6,2017,sext,False,Saturday,4
2398,,Blue note?,April 20,2017,sext,False,Thursday,4
19151,,Squire message,September 15,2016,sext,False,Thursday,4
85837,IT'S BETTER THIS WAY,Something dirty kept in a cell?,March 16,2014,sext,False,Sunday,4

In [265]:

common_words = set(oed['word']).intersection(cw_unique['answer'])
print(len(common_words))
common_words

common_df = pd.merge(left=cw_unique, right=oed, how='inner', left_on='answer', 
                     right_on='word' )[['word', 'date', 'year_x', 'month', 'year_y']]
common_df.drop_duplicates()

14

           word          date  year_x      month year_y
0      flexagon    February 5    2017       June   2014
3   unobtainium   December 31    2016   December   2014
6          vape    November 2    2016       June   2015
9    hoverboard        May 23    2016  September   2015
12      earworm     October 1    2015      March   2015
15    photobomb   February 28    2015       June   2015
21       selfie    January 23    2015       June   2014
24     locavore   November 21    2014   December   2015
27        emoji     August 17    2014   December   2013
28   javascript        June 6    2014       June   2015
31       carnap        May 18    2014       June   2015
34        twerk      March 30    2014       June   2015
40      retweet       March 1    2014       June   2015
46      netbook   November 18    2012       June   2015

In [133]:
import datetime

In [277]:
def monthToNum(mon):
    return{
        'January' : 1,
        'February' : 2,
        'March' : 3,
        'April' : 4,
        'May' : 5,
        'June' : 6,
        'July' : 7,
        'August' : 8,
        'September' : 9, 
        'October' : 10,
        'November' : 11,
        'December' : 12
    }[mon]

def oed_date(x):
    return datetime.date(int(x['year_y']), monthToNum(x['month']), 1,)

def cw_date(x):
    space, mon, day = re.split(' ', x['date'].rstrip())
    return datetime.date(int(x['year_x']), monthToNum(mon), 1)

def faster(x):
    if x['oed_date'] < x['cw_date']:
        return 'OED first'
    else:
        return 'CW first'

def find_start(x):
    if x['oed_date'] < x['cw_date']:
        return x['oed_date']
    else:
        return x['cw_date']
    
def find_finish(x):
    if x['oed_date'] >= x['cw_date']:
        return x['oed_date']
    else:
        return x['cw_date']

In [267]:
common_df['oed_date']=common_df.apply(oed_date, axis=1)
common_df['cw_date']=common_df.apply(cw_date, axis=1)
common_df['first_to_use']=common_df.apply(faster, axis=1)
common_df['Start']=common_df.apply(find_start, axis=1)
common_df['Finish']=common_df.apply(find_finish, axis=1)
common_df.drop_duplicates()

,word,date,year_x,month,year_y,oed_date,cw_date,first_to_use,Start,Finish
0,flexagon,February 5,2017,June,2014,2014-06-01,2017-02-01,OED first,2014-06-01,2017-02-01
3,unobtainium,December 31,2016,December,2014,2014-12-01,2016-12-01,OED first,2014-12-01,2016-12-01
6,vape,November 2,2016,June,2015,2015-06-01,2016-11-01,OED first,2015-06-01,2016-11-01
9,hoverboard,May 23,2016,September,2015,2015-09-01,2016-05-01,OED first,2015-09-01,2016-05-01
12,earworm,October 1,2015,March,2015,2015-03-01,2015-10-01,OED first,2015-03-01,2015-10-01
15,photobomb,February 28,2015,June,2015,2015-06-01,2015-02-01,CW first,2015-02-01,2015-06-01
21,selfie,January 23,2015,June,2014,2014-06-01,2015-01-01,OED first,2014-06-01,2015-01-01
24,locavore,November 21,2014,December,2015,2015-12-01,2014-11-01,CW first,2014-11-01,2015-12-01
27,emoji,August 17,2014,December,2013,2013-12-01,2014-08-01,OED first,2013-12-01,2014-08-01
28,javascript,June 6,2014,June,2015,2015-06-01,2014-06-01,CW first,2014-06-01,2015-06-01
31,carnap,May 18,2014,June,2015,2015-06-01,2014-05-01,CW first,2014-05-01,2015-06-01
34,twerk,March 30,2014,June,2015,2015-06-01,2014-03-01,CW first,2014-03-01,2015-06-01
40,retweet,March 1,2014,June,2015,2015-06-01,2014-03-01,CW first,2014-03-01,2015-06-01
46,netbook,November 18,2012,June,2015,2015-06-01,2012-11-01,CW first,2012-11-01,2015-06-01

In [268]:
df = common_df.drop_duplicates()[['word', 'Start', 'Finish', 'first_to_use']]
df.columns = ['Task', 'Start', 'Finish', 'Resource']
df.head()

           Task       Start      Finish   Resource
0      flexagon  2014-06-01  2017-02-01  OED first
3   unobtainium  2014-12-01  2016-12-01  OED first
6          vape  2015-06-01  2016-11-01  OED first
9    hoverboard  2015-09-01  2016-05-01  OED first
12      earworm  2015-03-01  2015-10-01  OED first

In [269]:
import plotly.plotly as py
import plotly.figure_factory as ff

df_gantt = [dict(Task=x[1][0], Start=x[1][1], Finish=x[1][2], Resource=x[1][3]) for x in df.iterrows()]

fig = ff.create_gantt(df_gantt, index_col='Resource', title='Time Between NYT CW and OED Debuts', 
                      show_colorbar=True, showgrid_x=True, showgrid_y=True)
py.iplot(fig, filename='gantt-simple-gantt-chart', world_readable=True)

In [271]:
ud = pd.read_csv('ud_3.csv')
ud = ud.dropna()
ud['phrase']=ud['phrase'].map(str)

oed['word']=oed['word'].map(lambda x: x.lower())
ud['phrase']=ud['phrase'].map(lambda x: x.lower())
ud.head()

,submit_date,down_votes,up_votes,meaning,date,phrase
0,"May 01, 2003",1612,1717,another word for tight,May 2,fye
1,"December 12, 2003",792,3728,forciby volunteered. A task that was once vol...,Apr 11,voluntold
2,"February 05, 2010",592,1866,When you inadvertently reach for a beer that d...,Apr 18,ghost beer
3,"March 26, 2017",2665,1993,Unapologetic un-PC alpha male conservative fan...,Mar 28,breitbastard
4,"January 24, 2017",862,1676,To masturbate at work while on the clock.,May 1,beat out a paycheck

In [282]:
common_words = set(cw_unique['answer']).intersection(ud['phrase'])

In [283]:
len(common_words)

34

In [284]:
common_words

{'adhd',
 'bae',
 'besties',
 'biodome',
 'cyber',
 'deets',
 'dubstep',
 'earworm',
 'facepalm',
 'foodie',
 'frenemy',
 'haterade',
 'humblebrag',
 'instagram',
 'janky',
 'kidult',
 'lifehack',
 'locavore',
 'mansplain',
 'mcdreamy',
 'nsfw',
 'obamania',
 'overshare',
 'photobomb',
 'potus',
 'selfie',
 'sexile',
 'shaka',
 'showmance',
 'snarky',
 'srsly',
 'twerk',
 'unobtainium',
 'vuvuzela'}

In [287]:
cw_unique

,title,clue,date,year,answer,unique,day,answer_count
5,,Company concerned with net profits?,December 16,2016,serviceprovider,True,Friday,1
14,,"Server of pink champagne on ice, in song",December 16,2016,hotelcalifornia,True,Friday,1
15,,Is perfectly punctual,December 16,2016,arrivesonthedot,True,Friday,1
17,,Workshop,December 16,2016,trainingseminar,True,Friday,1
41,,"""Rent"" showstopper",December 16,2016,lavieboheme,True,Friday,1
50,,Olden,December 16,2016,ofthepast,True,Friday,1
61,,"""___ Please, We're British"" (1971 stage farce)",December 16,2016,nosex,True,Friday,1
89,,"""Young 'uns, yer cuzzins are here"" and others?",December 8,2016,paannouncements,True,Thursday,1
101,,What Stephen King's editor provided for a 1986...,December 8,2016,itsupport,True,Thursday,1
153,,"Player of Molly on ""Mike &amp; Molly""",December 9,2016,melissamccarthy,True,Friday,1
159,,Received high marks,December 9,2016,gotas,True,Friday,1
171,,Where Roger Ebert's reviews appeared for 47 years,December 9,2016,chicagosuntimes,True,Friday,1
181,,"___ Mayer, Yahoo C.E.O. beginning in 2012",December 9,2016,marissa,True,Friday,1
192,,Pair on Mississippi's state quarter,December 9,2016,magnolias,True,Friday,1
217,,"Bombing, as a joke",December 15,2016,fallingflat,True,Thursday,1
229,,Discriminatory part of post-Reconstruction leg...,December 15,2016,grandfatherclause,True,Thursday,1
235,,Short-stemmed vessel,December 15,2016,parfaitglass,True,Thursday,1
257,,Joe Six-Pack,December 15,2016,regularguy,True,Thursday,1
306,,*One of a dozen for a sweetheart,December 7,2016,cutrose,True,Wednesday,1
313,,*Something to make up,December 7,2016,lostground,True,Wednesday,1
333,,Some street scenes,December 7,2016,urbanart,True,Wednesday,1
334,,Spy communication spots,December 7,2016,deaddrops,True,Wednesday,1
347,,Blows the whistle,December 7,2016,stopsplay,True,Wednesday,1
351,,Working diligently,December 7,2016,hardatit,True,Wednesday,1
392,,"Following the shaded squares, the end to a sea...",December 6,2016,meandmydrum,True,Tuesday,1
412,,"Mr. ___ of ""The Karate Kid""",December 6,2016,miyagi,True,Tuesday,1
455,,It grabs one's attention,December 5,2016,necksnapper,True,Monday,1
461,,Boastful sort,December 5,2016,chestbeater,True,Monday,1
490,,"Keyboard, monitor, mouse and other devices",December 5,2016,peripherals,True,Monday,1
505,,Invitation to a questioner,December 5,2016,askaway,True,Monday,2
...,...,...,...,...,...,...,...,...
127691,,See 40-Across,August 7,2012,notfollowingyou,True,Tuesday,1
127707,,Use a whisk on,August 7,2012,handmix,True,Tuesday,1
127723,,Didn't compromise,August 7,2012,stoodfast,True,Tuesday,1
127727,,Hunk on display,August 7,2012,gqmodel,True,Tuesday,1
127755,,Massage message?,August 10,2012,thatfeelssogood,True,Friday,1
127758,,Sent some cybernotes,August 10,2012,imed,True,Friday,4
127779,,Instant-book title of 1981 or 2011,August 10,2012,theroyalwedding,True,Friday,1
127827,,*Result of a financial panic,August 6,2012,bankrun,True,Monday,1
127828,,*Tight braid,August 6,2012,cornrow,True,Monday,1
127840,,*Precipitous drop in cost,August 6,2012,pricedive,True,Monday,1
127867,,Detects like a bloodhound,August 6,2012,sniffsout,True,Monday,1
127895,SINGLE-MINDED,"Disappointing ""Who's with me?"" response?",August 5,2012,showofhand,True,Sunday,1
127896,SINGLE-MINDED,Work to maintain a C average?,August 5,2012,hitthebook,True,Sunday,1
127900,SINGLE-MINDED,Mention that you know a secret?,August 5,2012,spillthebean,True,Sunday,1
127908,SINGLE-MINDED,One who's read an encyclopedia's first volume?,August 5,2012,manofletter,True,Sunday,1
127912,SINGLE-MINDED,Podunk's directory?,August 5,2012,yellowpage,True,Sunday,1
127919,SINGLE-MINDED,Having finished just one month of a job?,August 5,2012,wetbehindtheear,True,Sunday,1
127926,SINGLE-MINDED,What one with a small nest egg enjoys?,August 5,2012,goldenyear,True,Sunday,1
127930,SINGLE-MINDED,Despot's concession?,August 5,2012,billofright,True,Sunday,1
127938,SINGLE-MINDED,Occasional klutz?,August 5,2012,butterfinger,True,Sunday,1
127942,SINGLE-MINDED,Beginning magician's arsenal?,August 5,2012,bagoftrick,True,Sunday,1
127943,SINGLE-MINDED,Go on a brief youthful binge?,August 5,2012,sowonesoat,True,Sunday,1
127980,SINGLE-MINDED,"""Happens sometimes""",August 5,2012,itcan,True,Sunday,1
128009,SINGLE-MINDED,Cheers on,August 5,2012,rootsfor,True,Sunday,1
128060,,Handle online,August 9,2012,screenname,True,Thursday,1
128073,,Society add-ons,August 9,2012,debutantes,True,Thursday,1
128082,,1984 U.S. Olympic gold medalist in gymnastics,August 9,2012,bartconner,True,Thursday,1
128086,,"""Fame"" actress",August 9,2012,niapeeples,True,Thursday,1
128090,,"""You betcha!""",August 9,2012,yesindeedy,True,Thursday,1
128095,,Roman 112,August 9,2012,cxii,True,Thursday,1

In [291]:
common_df = pd.merge(left=cw_unique, right=ud, how='inner', left_on='answer', 
                     right_on='phrase')[['answer', 'date_x', 'year', 'submit_date']]
common_df.drop_duplicates()
common_df.columns = ['word', 'xword_date', 'xword_year', 'ud_submit_date']
common_df

           word     xword_date  xword_year       ud_submit_date
0         janky    February 19        2017       March 25, 2003
1       besties     February 4        2017     October 19, 2004
2        sexile     February 5        2017    February 25, 2003
3           bae     February 1        2017      August 11, 2006
4   unobtainium    December 31        2016      August 16, 2003
5     showmance    December 19        2016        July 17, 2006
6      lifehack     October 28        2016    December 06, 2005
7       dubstep       April 15        2016      August 23, 2010
8         deets        June 26        2016   September 30, 2004
9      haterade       March 25        2016        July 24, 2003
10        srsly    February 13        2016     October 06, 2006
11      earworm      October 1        2015     October 13, 2004
12    mansplain        June 26        2015    February 05, 2010
13     mcdreamy        June 27        2015   September 27, 2006
14       snarky         June 5        2015     October 09, 2002
15    photobomb    February 28        2015    November 16, 2009
16    photobomb    February 28        2015        June 27, 2008
17       selfie     January 23        2015        July 29, 2009
18     obamania    November 29        2014     January 16, 2008
19     locavore    November 21        2014   September 07, 2006
20        potus   September 30        2014     January 29, 2017
21        potus   September 30        2014        July 30, 2005
22   humblebrag   September 19        2014         May 02, 2011
23    overshare         May 30        2014    December 14, 2003
24         nsfw        April 2        2014   September 12, 2003
25        twerk       March 30        2014    November 30, 2012
26       foodie    February 27        2014    February 25, 2005
27         adhd     February 6        2014    December 05, 2004
28     facepalm     January 18        2014    February 10, 2004
29       kidult     November 2        2013     January 09, 2006
30        shaka        July 21        2013    December 22, 2003
31        cyber        June 10        2013    February 22, 2004
32      biodome     February 1        2013        July 19, 2005
33      frenemy     February 1        2013         May 05, 2004
34    instagram    November 10        2012         May 15, 2011
35     vuvuzela   September 28        2012        June 13, 2010

In [38]:
ud_common = ud[ud['phrase'].isin(list(common_words))]

In [39]:
oed_common = oed[oed['word'].isin(list(common_words))]

In [40]:
pd.merge(oed_common, ud_common, how='outer', left_on='word', right_on='phrase')

,entry_type,year,part_of_speech,word,month,acronym,word_length,dash,submit_date,down_votes,up_votes,meaning,date,phrase
0,new word entry,2015,v.,autotune,June,False,1,False,"February 01, 2007",1011,5743,Pitch correction software specifically for voc...,29-Apr,autotune
1,new sub-entry,2015,v.,autotune,June,False,1,False,"February 01, 2007",1011,5743,Pitch correction software specifically for voc...,29-Apr,autotune
2,new word sense,2015,v.,autotune,June,False,1,False,"February 01, 2007",1011,5743,Pitch correction software specifically for voc...,29-Apr,autotune
3,new word entry,2015,v.,fap,June,False,1,False,"October 11, 2002",7976,20862,The onomatopoeic representation of masturbatio...,8-Sep,fap
4,new sub-entry,2015,v.,fap,June,False,1,False,"October 11, 2002",7976,20862,The onomatopoeic representation of masturbatio...,8-Sep,fap
5,new word sense,2015,v.,fap,June,False,1,False,"October 11, 2002",7976,20862,The onomatopoeic representation of masturbatio...,8-Sep,fap
6,new word entry,2015,n.,hot mess,June,False,2,False,"February 13, 2007",5114,14909,When ones thoughts or appearance are in a stat...,4-Nov,hot mess
7,new sub-entry,2015,n.,hot mess,June,False,2,False,"February 13, 2007",5114,14909,When ones thoughts or appearance are in a stat...,4-Nov,hot mess
8,new word sense,2015,n.,hot mess,June,False,2,False,"February 13, 2007",5114,14909,When ones thoughts or appearance are in a stat...,4-Nov,hot mess
9,new word entry,2015,int. and adj.,meh,June,False,1,False,"November 16, 2002",2422,17988,Indifference; to be used when one simply does ...,22-May,meh
10,new sub-entry,2015,int. and adj.,meh,June,False,1,False,"November 16, 2002",2422,17988,Indifference; to be used when one simply does ...,22-May,meh
11,new word sense,2015,int. and adj.,meh,June,False,1,False,"November 16, 2002",2422,17988,Indifference; to be used when one simply does ...,22-May,meh
12,new word entry,2015,n.,photobomb,June,False,1,False,"November 16, 2009",834,3130,An otherwise normal photo that has been ruined...,28-Sep,photobomb
13,new word entry,2015,n.,photobomb,June,False,1,False,"June 27, 2008",1540,8975,(verb)- to drop in a photo unexpectedly...to h...,5-Dec,photobomb
14,new word entry,2015,v.,photobomb,June,False,1,False,"November 16, 2009",834,3130,An otherwise normal photo that has been ruined...,28-Sep,photobomb
15,new word entry,2015,v.,photobomb,June,False,1,False,"June 27, 2008",1540,8975,(verb)- to drop in a photo unexpectedly...to h...,5-Dec,photobomb
16,new sub-entry,2015,n.,photobomb,June,False,1,False,"November 16, 2009",834,3130,An otherwise normal photo that has been ruined...,28-Sep,photobomb
17,new sub-entry,2015,n.,photobomb,June,False,1,False,"June 27, 2008",1540,8975,(verb)- to drop in a photo unexpectedly...to h...,5-Dec,photobomb
18,new sub-entry,2015,v.,photobomb,June,False,1,False,"November 16, 2009",834,3130,An otherwise normal photo that has been ruined...,28-Sep,photobomb
19,new sub-entry,2015,v.,photobomb,June,False,1,False,"June 27, 2008",1540,8975,(verb)- to drop in a photo unexpectedly...to h...,5-Dec,photobomb
20,new word sense,2015,n.,photobomb,June,False,1,False,"November 16, 2009",834,3130,An otherwise normal photo that has been ruined...,28-Sep,photobomb
21,new word sense,2015,n.,photobomb,June,False,1,False,"June 27, 2008",1540,8975,(verb)- to drop in a photo unexpectedly...to h...,5-Dec,photobomb
22,new word sense,2015,v.,photobomb,June,False,1,False,"November 16, 2009",834,3130,An otherwise normal photo that has been ruined...,28-Sep,photobomb
23,new word sense,2015,v.,photobomb,June,False,1,False,"June 27, 2008",1540,8975,(verb)- to drop in a photo unexpectedly...to h...,5-Dec,photobomb
24,new word entry,2015,n.,photobombing,June,False,1,False,"May 06, 2008",392,3349,"Intentionally posing in other people's photos,...",20-Jun,photobombing
25,new sub-entry,2015,n.,photobombing,June,False,1,False,"May 06, 2008",392,3349,"Intentionally posing in other people's photos,...",20-Jun,photobombing
26,new word sense,2015,n.,photobombing,June,False,1,False,"May 06, 2008",392,3349,"Intentionally posing in other people's photos,...",20-Jun,photobombing
27,new word entry,2015,n.,sexting,June,False,1,False,"April 06, 2010",8279,8608,"The unauthorized, non-maritime use of sextants...",14-Jul,sexting
28,new word entry,2015,n.,sexting,June,False,1,False,"April 07, 2008",7195,11786,v: the act of text messaging someone in the ho...,6-Dec,sexting
29,new sub-entry,2015,n.,sexting,June,False,1,False,"April 06, 2010",8279,8608,"The unauthorized, non-maritime use of sextants...",14-Jul,sexting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,new sub-entry,2015,n.,twerking,June,False,1,False,"December 14, 2011",9299,8791,Also known as dirty dancing. When a woman slam...,30-Aug,twerking
49,new word sense,2015,adj.,twerking,June,False,1,False,"December 14, 2011",9299,8791,Also known as dirty dancing. When a woman slam...,30-Aug,twerking
50,new word sense,2015,n.,twerking,June,False,1,False,"December 14, 2011",9299,8791,Also known as dirty dancing. When a woman slam...,30-Aug,twerking
51,new word entry,2014,n. and adj.,flexitarian,June,False,1,False,"April 14, 2016",3930,4115,"An occasional meat eater. Not a vegetarian, ma...",21-Apr,flexitarian
52,new word entry,2014,n. and adj.,flexitarian,June,False,1,False,"May 27, 2004",370,578,some one who essentially eats just vegetables ...,15-Sep,flexitarian
53,new sub-entry,2014,n. and adj.,flexitarian,June,False,1,False,"April 14, 2016",3930,4115,"An occasional meat eater. Not a vegetarian, ma...",21-Apr,flexitarian
54,new sub-entry,2014,n. and adj.,flexitarian,June,False,1,False,"May 27, 2004",370,578,some one who essentially eats just vegetables ...,15-Sep,flexitarian
55,new word sense,2014,n. and adj.,flexitarian,June,False,1,False,"April 14, 2016",3930,4115,"An occasional meat eater. Not a vegetarian, ma...",21-Apr,flexitarian
56,new word sense,2014,n. and adj.,flexitarian,June,False,1,False,"May 27, 2004",370,578,some one who essentially eats just vegetables ...,15-Sep,flexitarian
57,new word entry,2014,n.,selfie,June,False,1,False,"July 29, 2009",2560,7602,A picture taken of yourself that is planned to...,12-Oct,selfie
58,new sub-entry,2014,n.,selfie,June,False,1,False,"July 29, 2009",2560,7602,A picture taken of yourself that is planned to...,12-Oct,selfie
59,new word sense,2014,n.,selfie,June,False,1,False,"July 29, 2009",2560,7602,A picture taken of yourself that is planned to...,12-Oct,selfie
60,new word entry,2014,n.,upcycling,June,False,1,False,"November 08, 2007",5705,3293,The practice of converting waste materials int...,21-May,upcycling
61,new sub-entry,2014,n.,upcycling,June,False,1,False,"November 08, 2007",5705,3293,The practice of converting waste materials int...,21-May,upcycling
62,new word sense,2014,n.,upcycling,June,False,1,False,"November 08, 2007",5705,3293,The practice of converting waste materials int...,21-May,upcycling
63,new word entry,2014,n.,unobtainium,December,False,1,False,"August 16, 2003",57,356,An imaginary unavailable material used humouro...,8-May,unobtainium
64,new sub-entry,2014,n.,unobtainium,December,False,1,False,"August 16, 2003",57,356,An imaginary unavailable material used humouro...,8-May,unobtainium
65,new word sense,2014,n.,unobtainium,December,False,1,False,"August 16, 2003",57,356,An imaginary unavailable material used humouro...,8-May,unobtainium
66,new word entry,2015,n.2,earworm,March,False,1,False,"October 13, 2004",587,2307,"A song that sticks in your mind, and will not ...",11-Jul,earworm
67,new sub-entry,2015,n.2,earworm,March,False,1,False,"October 13, 2004",587,2307,"A song that sticks in your mind, and will not ...",11-Jul,earworm
68,new word sense,2015,n.2,earworm,March,False,1,False,"October 13, 2004",587,2307,"A song that sticks in your mind, and will not ...",11-Jul,earworm
69,new word entry,2013,n.3,dap,December,False,1,False,"March 10, 2004",1754,3735,"The knocking of fists together as a greeting, ...",18-Jan,dap
70,new word entry,2015,n.5,gram,December,False,1,False,"June 30, 2013",9086,6257,To take a photo using Instagram.,13-Oct,gram
71,new sub-entry,2015,n.5,gram,December,False,1,False,"June 30, 2013",9086,6257,To take a photo using Instagram.,13-Oct,gram
72,new word sense,2015,n.5,gram,December,False,1,False,"June 30, 2013",9086,6257,To take a photo using Instagram.,13-Oct,gram
73,new word entry,2013,n.4,ha,December,False,1,False,"October 11, 2005",1686,10284,"awknowledgement of someones comment or joke, b...",15-Oct,ha
74,new word entry,2013,adv.,hapa,December,False,1,False,"January 15, 2004",413,774,It literally means half in Hawaiian. It was o...,11-Aug,hapa
75,new word entry,2015,n.,locavore,December,False,1,False,"September 07, 2006",1161,533,Noune. A person whose diet focuses on foods g...,14-Dec,locavore
76,new sub-entry,2015,n.,locavore,December,False,1,False,"September 07, 2006",1161,533,Noune. A person whose diet focuses on foods g...,14-Dec,locavore
77,new word sense,2015,n.,locavore,December,False,1,False,"September 07, 2006",1161,533,Noune. A person whose diet focuses on foods g...,14-Dec,locavore

In [8]:
oed[oed['word']=='mooc']

Empty DataFrame
Columns: [entry_type, year, part_of_speech, word, month]
Index: []